/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2015 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

// int __fastcall _cxa_finalize(_DWORD); weak
signed int __fastcall j_HAL_getCameraInfo(int a1, int a2, int a3, int a4);
void *__fastcall j_HAL_getNumberOfCameras(int a1, int a2, int a3);
// int _android_log_print(_DWORD, _DWORD, const char *, ...); weak
android::CameraHalInterface *__fastcall android::CameraHalInterface::CameraHalInterface(android::CameraHalInterface *this, int a2, int a3);
// void __cdecl operator delete(void *); idb
// _DWORD __cdecl android::RefBase::decStrong(android::RefBase *this, const void *); idb
android::CameraHalInterface *__fastcall android::CameraHalInterface::~CameraHalInterface(android::CameraHalInterface *this);
// void *dlopen(const char *file, int mode);
// char *dlerror(void);
// void *dlsym(void *handle, const char *name);
android::CameraHalInterface *__fastcall android::CameraHalInterface::loadCameraHardwareCore(android::CameraHalInterface *this, int a2, int a3);
// _DWORD __cdecl android::RefBase::incStrong(android::RefBase *this, const void *); idb
// int dlclose(void *handle);
android::CameraHalInterface *__fastcall android::CameraHalInterface::~CameraHalInterface(android::CameraHalInterface *this);
int __fastcall android::CameraHalInterface::setPreviewWindow(int a1);
int __fastcall android::CameraHalInterface::setCallbacks(int a1);
int __fastcall android::CameraHalInterface::enableMsgType(android::CameraHalInterface *this, int a2);
int __fastcall android::CameraHalInterface::disableMsgType(android::CameraHalInterface *this, int a2);
int __fastcall android::CameraHalInterface::msgTypeEnabled(android::CameraHalInterface *this, int a2);
int __fastcall android::CameraHalInterface::startPreview(android::CameraHalInterface *this);
int __fastcall android::CameraHalInterface::stopPreview(android::CameraHalInterface *this);
int __fastcall android::CameraHalInterface::previewEnabled(android::CameraHalInterface *this);
int __fastcall android::CameraHalInterface::startRecording(android::CameraHalInterface *this);
int __fastcall android::CameraHalInterface::stopRecording(android::CameraHalInterface *this);
int __fastcall android::CameraHalInterface::recordingEnabled(android::CameraHalInterface *this);
int __fastcall android::CameraHalInterface::storeMetaDataInBuffers(android::CameraHalInterface *this, bool a2);
int __fastcall android::CameraHalInterface::releaseRecordingFrame(android::CameraHalInterface *this, const void *a2);
int __fastcall android::CameraHalInterface::autoFocus(android::CameraHalInterface *this);
int __fastcall android::CameraHalInterface::cancelAutoFocus(android::CameraHalInterface *this);
int __fastcall android::CameraHalInterface::takePicture(android::CameraHalInterface *this);
int __fastcall android::CameraHalInterface::cancelPicture(android::CameraHalInterface *this);
int __fastcall android::CameraHalInterface::sendCommand(android::CameraHalInterface *this, int a2, int a3, int a4);
int __fastcall android::CameraHalInterface::release(android::CameraHalInterface *this);
int __fastcall android::CameraHalInterface::dump(android::CameraHalInterface *this, int a2);
int __fastcall android::CameraHalInterface::setParameters(android::CameraHalInterface *this, const android::CameraParameters *a2);
android::CameraHalInterface *__fastcall android::CameraHalInterface::getParameters(android::CameraHalInterface *this, int a2);
// void abort(void);
// int fprintf(FILE *stream, const char *format, ...);
// int __fastcall _aeabi_memcpy(_DWORD); weak
// int __fastcall _aeabi_memset(_DWORD, _DWORD, _DWORD); weak
// int dladdr(void); weak
// int __fastcall _snprintf_chk(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int __fastcall _gnu_Unwind_Find_exidx(_DWORD, _DWORD); weak
int sub_17A8();
int (*__fastcall sub_17C8(int (*result)(void)))(void);
int __fastcall android::CameraHalInterface::setPreviewWindow(int a1);
int __fastcall android::CameraHalInterface::setCallbacks(int a1);
int __fastcall android::CameraHalInterface::enableMsgType(android::CameraHalInterface *this, int a2);
int __fastcall android::CameraHalInterface::disableMsgType(android::CameraHalInterface *this, int a2);
int __fastcall android::CameraHalInterface::msgTypeEnabled(android::CameraHalInterface *this, int a2);
int __fastcall android::CameraHalInterface::startPreview(android::CameraHalInterface *this);
int __fastcall android::CameraHalInterface::stopPreview(android::CameraHalInterface *this);
int __fastcall android::CameraHalInterface::previewEnabled(android::CameraHalInterface *this);
int __fastcall android::CameraHalInterface::storeMetaDataInBuffers(android::CameraHalInterface *this, bool a2);
int __fastcall android::CameraHalInterface::startRecording(android::CameraHalInterface *this);
int __fastcall android::CameraHalInterface::stopRecording(android::CameraHalInterface *this);
int __fastcall android::CameraHalInterface::recordingEnabled(android::CameraHalInterface *this);
int __fastcall android::CameraHalInterface::releaseRecordingFrame(android::CameraHalInterface *this, const void *a2);
int __fastcall android::CameraHalInterface::autoFocus(android::CameraHalInterface *this);
int __fastcall android::CameraHalInterface::cancelAutoFocus(android::CameraHalInterface *this);
int __fastcall android::CameraHalInterface::takePicture(android::CameraHalInterface *this);
int __fastcall android::CameraHalInterface::cancelPicture(android::CameraHalInterface *this);
int __fastcall android::CameraHalInterface::dump(android::CameraHalInterface *this, int a2);
int __fastcall android::CameraHalInterface::setParameters(android::CameraHalInterface *this, const android::CameraParameters *a2);
android::CameraHalInterface *__fastcall android::CameraHalInterface::getParameters(android::CameraHalInterface *this, int a2);
int __fastcall android::CameraHalInterface::sendCommand(android::CameraHalInterface *this, int a2, int a3, int a4);
int __fastcall android::CameraHalInterface::release(android::CameraHalInterface *this);
android::CameraHalInterface *__fastcall android::CameraHalInterface::~CameraHalInterface(android::CameraHalInterface *this);
android::CameraHalInterface *__fastcall android::CameraHalInterface::~CameraHalInterface(android::CameraHalInterface *this);
android::CameraHalInterface *__fastcall android::CameraHalInterface::loadCameraHardwareCore(android::CameraHalInterface *this, int a2, int a3);
android::CameraHalInterface *__fastcall android::CameraHalInterface::CameraHalInterface(android::CameraHalInterface *this, int a2, int a3);
void *__fastcall HAL_getNumberOfCameras(int a1, int a2, int a3);
signed int __fastcall HAL_getCameraInfo(int a1, int a2, int a3, int a4);
signed int __fastcall sub_1FD8(int a1, int a2, unsigned int a3, unsigned int a4);
signed int __fastcall sub_231C(int a1, int a2, unsigned int a3, int a4, int *a5);
signed int __fastcall sub_23C0(int a1, int a2, unsigned int a3, int a4);
signed int __fastcall sub_24E4(int a1, int a2, int a3);
void sub_2538();
void sub_2540();
signed int __fastcall sub_25DC(int a1, int a2, char a3);
void __fastcall sub_26F8(int a1, int a2, int a3);
int __fastcall sub_277C(int a1, int a2, int a3, int a4, int a5);
int __fastcall sub_2794(int _R0);
int __fastcall sub_279C(int _R0);
int __fastcall sub_27A4(int _R0);
void sub_27AC();
void sub_27F0();
int __fastcall sub_2804(int a1);
signed int __fastcall sub_2854(int a1, int a2, _DWORD *a3);
signed int __fastcall sub_2884(int a1, int a2, int a3);
signed int __fastcall sub_28C8(int a1, int a2, _QWORD *a3);
signed int __fastcall sub_28F8(int a1, int a2, int a3, int a4);
int __fastcall sub_2930(int a1);
signed int __fastcall sub_2938(int a1, int a2);
signed int __fastcall sub_2958(int a1);
int __fastcall sub_2970(int a1);
int __fastcall sub_2980(int a1, int a2);
int __fastcall sub_29A4(int a1, signed int a2);
int __fastcall sub_2A40(int result, signed int a2, int a3);
int __fastcall sub_2AD8(int a1, int a2);
__int64 __fastcall sub_2AFC(int a1, int a2);
int __fastcall sub_2BAC(int a1, int a2, int a3, int a4);
signed int __fastcall sub_2C80(int a1);
int __fastcall sub_2CCC(int a1, int a2);
void __fastcall sub_2D0C(int a1);
int __fastcall sub_2D24(int a1);
signed int __fastcall sub_2D2C(int a1, int a2, int a3, _DWORD *a4);
int __fastcall sub_2D88(int a1, int a2);
const char *__fastcall sub_2DD4(int a1, signed int a2);
int __fastcall sub_2DDC(int result);
void __fastcall sub_2DE4(int a1, int a2, int a3, int a4);
int __fastcall sub_2E18(int a1);
int sub_2E68(); // weak
int __fastcall sub_2FF8(int result, int a2, int a3, _DWORD *a4, int a5, int a6, int a7, _DWORD *a8);
int sub_36D0(); // weak
int __fastcall sub_36E4(int _R0);
int __fastcall sub_36EC(int _R0);
int __fastcall sub_36F4(int _R0);
int __fastcall sub_36FC(_DWORD *a1);
int __fastcall sub_3740(_DWORD *a1);
void sub_3784();
void sub_3788();
int __fastcall sub_3794(_DWORD *a1);
int __fastcall sub_3798(_DWORD *a1);

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN loc_24EC; // weak
void *off_5D18 = (void *)0x2979; // weak
void *off_5D68 = (void *)0x1CE9; // weak
int GLOBAL_OFFSET_TABLE_ = 0; // weak
void *off_6000 = &off_6000; // weak
_DWORD getCameraInfoFromHardware; // idb
int dword_60BC; // weak
int dword_60C0; // weak
int dword_60C4[]; // weak
int dword_60C8; // weak
_UNKNOWN unk_611C; // weak
// extern struct _IO_FILE *stderr;


//----- (000014F0) --------------------------------------------------------
signed int __fastcall j_HAL_getCameraInfo(int a1, int a2, int a3, int a4)
{
  return HAL_getCameraInfo(a1, a2, a3, a4);
}

//----- (000014FC) --------------------------------------------------------
void *__fastcall j_HAL_getNumberOfCameras(int a1, int a2, int a3)
{
  return HAL_getNumberOfCameras(a1, a2, a3);
}

//----- (00001574) --------------------------------------------------------
android::CameraHalInterface *__fastcall android::CameraHalInterface::CameraHalInterface(android::CameraHalInterface *this, int a2, int a3)
{
  return android::CameraHalInterface::CameraHalInterface(this, a2, a3);
}

//----- (000015EC) --------------------------------------------------------
android::CameraHalInterface *__fastcall android::CameraHalInterface::~CameraHalInterface(android::CameraHalInterface *this)
{
  return android::CameraHalInterface::~CameraHalInterface(this);
}

//----- (0000161C) --------------------------------------------------------
android::CameraHalInterface *__fastcall android::CameraHalInterface::loadCameraHardwareCore(android::CameraHalInterface *this, int a2, int a3)
{
  return android::CameraHalInterface::loadCameraHardwareCore(this, a2, a3);
}

//----- (00001640) --------------------------------------------------------
android::CameraHalInterface *__fastcall android::CameraHalInterface::~CameraHalInterface(android::CameraHalInterface *this)
{
  return android::CameraHalInterface::~CameraHalInterface(this);
}

//----- (0000164C) --------------------------------------------------------
int __fastcall android::CameraHalInterface::setPreviewWindow(int a1)
{
  return android::CameraHalInterface::setPreviewWindow(a1);
}

//----- (00001658) --------------------------------------------------------
int __fastcall android::CameraHalInterface::setCallbacks(int a1)
{
  return android::CameraHalInterface::setCallbacks(a1);
}

//----- (00001664) --------------------------------------------------------
int __fastcall android::CameraHalInterface::enableMsgType(android::CameraHalInterface *this, int a2)
{
  return android::CameraHalInterface::enableMsgType(this, a2);
}

//----- (00001670) --------------------------------------------------------
int __fastcall android::CameraHalInterface::disableMsgType(android::CameraHalInterface *this, int a2)
{
  return android::CameraHalInterface::disableMsgType(this, a2);
}

//----- (0000167C) --------------------------------------------------------
int __fastcall android::CameraHalInterface::msgTypeEnabled(android::CameraHalInterface *this, int a2)
{
  return android::CameraHalInterface::msgTypeEnabled(this, a2);
}

//----- (00001688) --------------------------------------------------------
int __fastcall android::CameraHalInterface::startPreview(android::CameraHalInterface *this)
{
  return android::CameraHalInterface::startPreview(this);
}

//----- (00001694) --------------------------------------------------------
int __fastcall android::CameraHalInterface::stopPreview(android::CameraHalInterface *this)
{
  return android::CameraHalInterface::stopPreview(this);
}

//----- (000016A0) --------------------------------------------------------
int __fastcall android::CameraHalInterface::previewEnabled(android::CameraHalInterface *this)
{
  return android::CameraHalInterface::previewEnabled(this);
}

//----- (000016AC) --------------------------------------------------------
int __fastcall android::CameraHalInterface::startRecording(android::CameraHalInterface *this)
{
  return android::CameraHalInterface::startRecording(this);
}

//----- (000016B8) --------------------------------------------------------
int __fastcall android::CameraHalInterface::stopRecording(android::CameraHalInterface *this)
{
  return android::CameraHalInterface::stopRecording(this);
}

//----- (000016C4) --------------------------------------------------------
int __fastcall android::CameraHalInterface::recordingEnabled(android::CameraHalInterface *this)
{
  return android::CameraHalInterface::recordingEnabled(this);
}

//----- (000016D0) --------------------------------------------------------
int __fastcall android::CameraHalInterface::storeMetaDataInBuffers(android::CameraHalInterface *this, bool a2)
{
  return android::CameraHalInterface::storeMetaDataInBuffers(this, a2);
}

//----- (000016DC) --------------------------------------------------------
int __fastcall android::CameraHalInterface::releaseRecordingFrame(android::CameraHalInterface *this, const void *a2)
{
  return android::CameraHalInterface::releaseRecordingFrame(this, a2);
}

//----- (000016E8) --------------------------------------------------------
int __fastcall android::CameraHalInterface::autoFocus(android::CameraHalInterface *this)
{
  return android::CameraHalInterface::autoFocus(this);
}

//----- (000016F4) --------------------------------------------------------
int __fastcall android::CameraHalInterface::cancelAutoFocus(android::CameraHalInterface *this)
{
  return android::CameraHalInterface::cancelAutoFocus(this);
}

//----- (00001700) --------------------------------------------------------
int __fastcall android::CameraHalInterface::takePicture(android::CameraHalInterface *this)
{
  return android::CameraHalInterface::takePicture(this);
}

//----- (0000170C) --------------------------------------------------------
int __fastcall android::CameraHalInterface::cancelPicture(android::CameraHalInterface *this)
{
  return android::CameraHalInterface::cancelPicture(this);
}

//----- (00001718) --------------------------------------------------------
int __fastcall android::CameraHalInterface::sendCommand(android::CameraHalInterface *this, int a2, int a3, int a4)
{
  return android::CameraHalInterface::sendCommand(this, a2, a3, a4);
}

//----- (00001724) --------------------------------------------------------
int __fastcall android::CameraHalInterface::release(android::CameraHalInterface *this)
{
  return android::CameraHalInterface::release(this);
}

//----- (00001730) --------------------------------------------------------
int __fastcall android::CameraHalInterface::dump(android::CameraHalInterface *this, int a2)
{
  return android::CameraHalInterface::dump(this, a2);
}

//----- (0000173C) --------------------------------------------------------
int __fastcall android::CameraHalInterface::setParameters(android::CameraHalInterface *this, const android::CameraParameters *a2)
{
  return android::CameraHalInterface::setParameters(this, a2);
}

//----- (00001748) --------------------------------------------------------
android::CameraHalInterface *__fastcall android::CameraHalInterface::getParameters(android::CameraHalInterface *this, int a2)
{
  return android::CameraHalInterface::getParameters(this, a2);
}

//----- (000017A8) --------------------------------------------------------
int sub_17A8()
{
  return _cxa_finalize(&off_6000);
}
// 14CC: using guessed type int __fastcall _cxa_finalize(_DWORD);
// 6000: using guessed type void *off_6000;

//----- (000017C8) --------------------------------------------------------
int (*__fastcall sub_17C8(int (*result)(void)))(void)
{
  if ( result )
    result = (int (*)(void))result();
  return result;
}

//----- (00001C20) --------------------------------------------------------
int __fastcall android::CameraHalInterface::setPreviewWindow(int a1)
{
  return (*(int (**)(void))(**(_DWORD **)(a1 + 8) + 8))();
}

//----- (00001C28) --------------------------------------------------------
int __fastcall android::CameraHalInterface::setCallbacks(int a1)
{
  return (*(int (**)(void))(**(_DWORD **)(a1 + 8) + 12))();
}

//----- (00001C38) --------------------------------------------------------
int __fastcall android::CameraHalInterface::enableMsgType(android::CameraHalInterface *this, int a2)
{
  return (*(int (**)(void))(**((_DWORD **)this + 2) + 16))();
}

//----- (00001C40) --------------------------------------------------------
int __fastcall android::CameraHalInterface::disableMsgType(android::CameraHalInterface *this, int a2)
{
  return (*(int (**)(void))(**((_DWORD **)this + 2) + 20))();
}

//----- (00001C48) --------------------------------------------------------
int __fastcall android::CameraHalInterface::msgTypeEnabled(android::CameraHalInterface *this, int a2)
{
  return (*(int (**)(void))(**((_DWORD **)this + 2) + 24))();
}

//----- (00001C50) --------------------------------------------------------
int __fastcall android::CameraHalInterface::startPreview(android::CameraHalInterface *this)
{
  return (*(int (**)(void))(**((_DWORD **)this + 2) + 28))();
}

//----- (00001C58) --------------------------------------------------------
int __fastcall android::CameraHalInterface::stopPreview(android::CameraHalInterface *this)
{
  return (*(int (**)(void))(**((_DWORD **)this + 2) + 32))();
}

//----- (00001C60) --------------------------------------------------------
int __fastcall android::CameraHalInterface::previewEnabled(android::CameraHalInterface *this)
{
  return (*(int (**)(void))(**((_DWORD **)this + 2) + 36))();
}

//----- (00001C68) --------------------------------------------------------
int __fastcall android::CameraHalInterface::storeMetaDataInBuffers(android::CameraHalInterface *this, bool a2)
{
  return (*(int (**)(void))(**((_DWORD **)this + 2) + 52))();
}

//----- (00001C70) --------------------------------------------------------
int __fastcall android::CameraHalInterface::startRecording(android::CameraHalInterface *this)
{
  return (*(int (**)(void))(**((_DWORD **)this + 2) + 40))();
}

//----- (00001C78) --------------------------------------------------------
int __fastcall android::CameraHalInterface::stopRecording(android::CameraHalInterface *this)
{
  return (*(int (**)(void))(**((_DWORD **)this + 2) + 44))();
}

//----- (00001C80) --------------------------------------------------------
int __fastcall android::CameraHalInterface::recordingEnabled(android::CameraHalInterface *this)
{
  return (*(int (**)(void))(**((_DWORD **)this + 2) + 48))();
}

//----- (00001C88) --------------------------------------------------------
int __fastcall android::CameraHalInterface::releaseRecordingFrame(android::CameraHalInterface *this, const void *a2)
{
  return (*(int (**)(void))(**((_DWORD **)this + 2) + 56))();
}

//----- (00001C90) --------------------------------------------------------
int __fastcall android::CameraHalInterface::autoFocus(android::CameraHalInterface *this)
{
  return (*(int (**)(void))(**((_DWORD **)this + 2) + 60))();
}

//----- (00001C98) --------------------------------------------------------
int __fastcall android::CameraHalInterface::cancelAutoFocus(android::CameraHalInterface *this)
{
  return (*(int (**)(void))(**((_DWORD **)this + 2) + 64))();
}

//----- (00001CA0) --------------------------------------------------------
int __fastcall android::CameraHalInterface::takePicture(android::CameraHalInterface *this)
{
  return (*(int (**)(void))(**((_DWORD **)this + 2) + 68))();
}

//----- (00001CA8) --------------------------------------------------------
int __fastcall android::CameraHalInterface::cancelPicture(android::CameraHalInterface *this)
{
  return (*(int (**)(void))(**((_DWORD **)this + 2) + 72))();
}

//----- (00001CB0) --------------------------------------------------------
int __fastcall android::CameraHalInterface::dump(android::CameraHalInterface *this, int a2)
{
  return (*(int (**)(void))(**((_DWORD **)this + 2) + 80))();
}

//----- (00001CB8) --------------------------------------------------------
int __fastcall android::CameraHalInterface::setParameters(android::CameraHalInterface *this, const android::CameraParameters *a2)
{
  return (*(int (**)(void))(**((_DWORD **)this + 2) + 88))();
}

//----- (00001CC0) --------------------------------------------------------
android::CameraHalInterface *__fastcall android::CameraHalInterface::getParameters(android::CameraHalInterface *this, int a2)
{
  android::CameraHalInterface *v2; // r4@1

  v2 = this;
  (*(void (**)(void))(**(_DWORD **)(a2 + 8) + 92))();
  return v2;
}

//----- (00001CD0) --------------------------------------------------------
int __fastcall android::CameraHalInterface::sendCommand(android::CameraHalInterface *this, int a2, int a3, int a4)
{
  return (*(int (**)(void))(**((_DWORD **)this + 2) + 76))();
}

//----- (00001CE0) --------------------------------------------------------
int __fastcall android::CameraHalInterface::release(android::CameraHalInterface *this)
{
  return (*(int (**)(void))(**((_DWORD **)this + 2) + 84))();
}

//----- (00001CE8) --------------------------------------------------------
android::CameraHalInterface *__fastcall android::CameraHalInterface::~CameraHalInterface(android::CameraHalInterface *this)
{
  android::CameraHalInterface *v1; // r4@1
  char *v2; // r5@1
  char *v3; // r1@1
  char *v4; // r3@3

  v1 = this;
  *(_DWORD *)this = &off_5D68;
  v2 = (char *)this + 8;
  v3 = (char *)*((_DWORD *)this + 2);
  if ( v3 )
  {
    android::RefBase::decStrong((android::RefBase *)&v3[*(_DWORD *)(*(_DWORD *)v3 - 12)], v2);
    *((_DWORD *)v1 + 2) = 0;
  }
  v4 = (char *)*((_DWORD *)v1 + 2);
  if ( v4 )
    android::RefBase::decStrong((android::RefBase *)&v4[*(_DWORD *)(*(_DWORD *)v4 - 12)], v2);
  return v1;
}
// 5D68: using guessed type void *;

//----- (00001D2C) --------------------------------------------------------
android::CameraHalInterface *__fastcall android::CameraHalInterface::~CameraHalInterface(android::CameraHalInterface *this)
{
  android::CameraHalInterface *v1; // r4@1

  v1 = this;
  android::CameraHalInterface::~CameraHalInterface(this);
  operator delete((void *)v1);
  return v1;
}

//----- (00001D40) --------------------------------------------------------
android::CameraHalInterface *__fastcall android::CameraHalInterface::loadCameraHardwareCore(android::CameraHalInterface *this, int a2, int a3)
{
  android::CameraHalInterface *v3; // r4@1
  int v4; // r8@1
  char *v5; // r0@3
  void (__fastcall *v6)(android::CameraHalInterface *, int); // r7@5
  int v8; // [sp+4h] [bp-1Ch]@1

  v8 = a2;
  v3 = this;
  v4 = a3;
  if ( !dword_60BC )
  {
    dword_60BC = (int)dlopen("libcamera_core.so", dword_60BC);
    if ( !dword_60BC )
    {
      v5 = dlerror();
      _android_log_print(6, "CameraHalInterface", "[CAMERA_EVENT]load [%s] FAILED [%s]", "libcamera_core.so", v5, v8);
      *(_DWORD *)v3 = 0;
      return v3;
    }
    _android_log_print(4, "CameraHalInterface", "[CAMERA_EVENT]load [%s] OK", "libcamera_core.so");
  }
  v6 = (void (__fastcall *)(android::CameraHalInterface *, int))dlsym((void *)dword_60BC, "openCameraHardwareCore");
  if ( v6 )
  {
    v6(v3, v4);
  }
  else
  {
    _android_log_print(6, "CameraHalInterface", "could not find function openCameraHardwareCore in libcamera_core.so");
    *(_DWORD *)v3 = 0;
  }
  return v3;
}
// 1550: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);
// 60BC: using guessed type int dword_60BC;

//----- (00001DE4) --------------------------------------------------------
android::CameraHalInterface *__fastcall android::CameraHalInterface::CameraHalInterface(android::CameraHalInterface *this, int a2, int a3)
{
  android::CameraHalInterface *v3; // r4@1
  char *v4; // r7@1
  _DWORD *v5; // r5@1
  char *v6; // r3@3
  char *v7; // r7@5
  _DWORD *v9; // [sp+4h] [bp-1Ch]@1
  int v10; // [sp+8h] [bp-18h]@1

  v9 = (_DWORD *)a2;
  v10 = a3;
  v3 = this;
  v4 = (char *)this + 8;
  *(_DWORD *)this = &off_5D68;
  *((_DWORD *)this + 2) = 0;
  *((_DWORD *)this + 1) = 0;
  android::CameraHalInterface::loadCameraHardwareCore((android::CameraHalInterface *)&v9, (int)this, a2);
  v5 = v9;
  if ( v9 )
    android::RefBase::incStrong((android::RefBase *)((char *)v9 + *(_DWORD *)(*v9 - 12)), v4);
  v6 = (char *)*((_DWORD *)v3 + 2);
  if ( v6 )
    android::RefBase::decStrong((android::RefBase *)&v6[*(_DWORD *)(*(_DWORD *)v6 - 12)], v4);
  v7 = (char *)v9;
  *((_DWORD *)v3 + 2) = v5;
  if ( v7 )
    android::RefBase::decStrong((android::RefBase *)&v7[*(_DWORD *)(*(_DWORD *)v7 - 12)], &v9);
  if ( *((_DWORD *)v3 + 2) )
    *((_DWORD *)v3 + 1) = 1;
  else
    _android_log_print(6, "CameraHalInterface", "loadCameraHardwareCore failed");
  return v3;
}
// 1550: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);
// 5D68: using guessed type void *off_5D68;

//----- (00001E6C) --------------------------------------------------------
void *__fastcall HAL_getNumberOfCameras(int a1, int a2, int a3)
{
  void *v3; // r0@1
  void *v4; // r7@1
  char *v5; // r0@2
  void *result; // r0@2
  int v7; // r6@3
  int *v8; // r4@3
  int v9; // r3@5
  int v10; // [sp+0h] [bp-30h]@1
  int v11; // [sp+4h] [bp-2Ch]@1
  int v12; // [sp+8h] [bp-28h]@1

  v10 = a1;
  v11 = a2;
  v12 = a3;
  v3 = dlopen("libcamera_core.so", 0);
  v4 = v3;
  if ( v3 )
  {
    v7 = 0;
    getCameraInfoFromHardware = dlsym(v3, "getCameraInfo");
    ((void (__fastcall *)(int *, int *))getCameraInfoFromHardware)(dword_60C4, &dword_60C0);
    v8 = &dword_60C8;
    _android_log_print(4, "CameraHalInterface", "numberOfCameras=%d", dword_60C0, v10, v11, v12);
    while ( 1 )
    {
      v8 += 11;
      if ( v7 >= dword_60C0 )
        break;
      _android_log_print(4, "CameraHalInterface", "sensorInfo[%d].cameraId=%d", v7, *(int *)((char *)v8 + 0xFFFFFFD0));
      _android_log_print(4, "CameraHalInterface", "sensorInfo[%d].facing=%d", v7, *(int *)((char *)v8 + 0xFFFFFFD4));
      v9 = v7++;
      _android_log_print(
        4,
        "CameraHalInterface",
        "sensorInfo[%d].orientation=%d",
        v9,
        *(int *)((char *)v8 + 0xFFFFFFD8));
    }
    dlclose(v4);
    result = (void *)dword_60C0;
  }
  else
  {
    v5 = dlerror();
    _android_log_print(6, "CameraHalInterface", "could not dlopen libcamera_core.so: %s", v5, v10, v11, v12);
    result = v4;
  }
  return result;
}
// 1550: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);
// 60C0: using guessed type int dword_60C0;
// 60C4: using guessed type int dword_60C4[];
// 60C8: using guessed type int dword_60C8;

//----- (00001F68) --------------------------------------------------------
signed int __fastcall HAL_getCameraInfo(int a1, int a2, int a3, int a4)
{
  int v4; // r5@1
  int i; // r2@1
  int *v6; // r4@4

  v4 = a2;
  for ( i = 0; i < dword_60C0; ++i )
  {
    if ( dword_60C4[11 * i] == a1 )
    {
      v6 = &dword_60C4[11 * i];
      _android_log_print(4, "CameraHalInterface", "Found a matching camera info for ID %d");
      *(_DWORD *)v4 = v6[1];
      *(_DWORD *)(v4 + 4) = v6[2];
      return 0;
    }
  }
  _android_log_print(6, "CameraHalInterface", "Unable to find matching camera info for ID %d", a1, a4);
  return -22;
}
// 1550: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);
// 60C0: using guessed type int dword_60C0;
// 60C4: using guessed type int dword_60C4[];

//----- (00001FD8) --------------------------------------------------------
signed int __fastcall sub_1FD8(int a1, int a2, unsigned int a3, unsigned int a4)
{
  unsigned int v4; // r5@1
  unsigned int v5; // r7@1
  int v6; // r10@1
  int v7; // r4@1
  int v8; // r11@2
  unsigned int v9; // r8@7
  int v10; // r9@7
  int v11; // r0@8
  int v12; // r2@9
  int v13; // r1@10
  signed int result; // r0@10
  int v15; // r3@19
  int v16; // r2@19
  int v17; // r0@19
  int v18; // r1@19
  int v19; // r2@37
  int v20; // r0@39
  int v21; // r1@39
  int v22; // r3@39
  unsigned int v23; // r1@40
  unsigned int v24; // r0@40
  int v25; // r1@42
  int v26; // r6@45
  char v27; // r1@45
  int v29; // r0@50
  unsigned int v35; // r0@51
  int v36; // [sp+4h] [bp-34h]@58
  int v37; // [sp+8h] [bp-30h]@6
  int v38; // [sp+Ch] [bp-2Ch]@22
  int v39; // [sp+10h] [bp-28h]@8

  v4 = a4;
  v5 = a3;
  v6 = a2;
  v7 = a1;
  if ( a3 >= a4 )
    goto LABEL_58;
  v8 = 0;
  do
  {
    v9 = v5 + 1;
    v10 = *(_BYTE *)(v6 + (v5 ^ 3));
    if ( !(v10 & 0x80) )
    {
      sub_2854(v7, 13, &v39);
      v11 = 4 * v10;
      if ( v10 & 0x40 )
        v12 = -4 - (v11 & 0xFC) + v39;
      else
        v12 = v11 + v39 + 4;
      v39 = v12;
LABEL_23:
      sub_2884(v7, 13, v12);
      ++v5;
      continue;
    }
    v13 = v10 & 0xF0;
    result = 9;
    if ( v13 > 159 )
    {
      if ( v13 > 191 )
      {
        if ( v13 == 192 )
        {
          switch ( v10 )
          {
            case 199:
              if ( !*(_BYTE *)(v6 + (v9 ^ 3)) || (unsigned int)*(_BYTE *)(v6 + (v9 ^ 3)) >= 0x10 )
                return 9;
              goto LABEL_55;
            case 192:
            case 193:
            case 194:
            case 195:
            case 196:
            case 197:
              v18 = 3;
              v16 = ((v10 & 7) + 1) | 0xA0000;
              v17 = v7;
              goto LABEL_33;
            case 200:
            case 201:
              v23 = *(_BYTE *)(v6 + (v9 ^ 3));
              v24 = v23 >> 4;
              if ( v10 == 200 )
                v24 = (v23 >> 4) | 0x10;
              v25 = v23 & 0xF;
              if ( (signed int)(v24 + v25) > 31 )
                return 9;
              v19 = (v25 + 1) | (v24 << 16);
              v20 = v7;
              v21 = 1;
              goto LABEL_53;
            case 198:
              v35 = *(_BYTE *)(v6 + (v9 ^ 3));
              if ( (signed int)((v35 & 0xF) + (v35 >> 4)) > 15 )
                return 9;
              v19 = ((v35 & 0xF) + 1) | (v35 >> 4 << 16);
              v20 = v7;
              v21 = 3;
LABEL_53:
              v22 = 5;
LABEL_54:
              sub_23C0(v20, v21, v19, v22);
              goto LABEL_55;
            default:
              return 9;
          }
          return 9;
        }
        if ( v13 != 208 )
          return result;
        if ( v10 & 8 )
          return 9;
        v18 = 1;
        v16 = ((v10 & 7) + 1) | 0x80000;
        v17 = v7;
LABEL_33:
        v15 = 5;
      }
      else
      {
        if ( v13 != 160 )
        {
          if ( v13 != 176 )
            return result;
          result = 9;
          switch ( v10 )
          {
            case 177:
              if ( v9 >= v4 )
                return 9;
              v19 = *(_BYTE *)(v6 + (v9 ^ 3));
              result = 9;
              if ( !*(_BYTE *)(v6 + (v9 ^ 3)) || v19 & 0xF0 )
                return result;
              v20 = v7;
              v21 = 0;
              v22 = 0;
              goto LABEL_54;
            case 178:
              if ( v9 >= v4 )
                return 9;
              v5 += 2;
              v26 = 0;
              v27 = 0;
              break;
            case 179:
              v22 = 1;
              v29 = *(_BYTE *)(v6 + (v9 ^ 3));
              _R1 = v29 << 12;
              __asm { UXTB16.W        R1, R1 }
              v19 = ((v29 & 0xF) + 1) | _R1;
              v20 = v7;
              v21 = 1;
              goto LABEL_54;
            case 176:
              goto LABEL_57;
            case 180:
            case 181:
            case 182:
            case 183:
              return result;
            default:
              v18 = 1;
              v15 = 1;
              v16 = ((v10 & 7) + 1) | 0x80000;
              v17 = v7;
              goto LABEL_34;
          }
          while ( 1 )
          {
            v26 |= (*(_BYTE *)(v6 + ((v5 - 1) ^ 3)) & 0x7F) << v27;
            if ( !(*(_BYTE *)(v6 + ((v5 - 1) ^ 3)) & 0x80) )
              break;
            _CF = v5 >= v4;
            v27 += 7;
            result = 9;
            ++v5;
            if ( _CF )
              return result;
          }
          sub_2854(v7, 13, &v37);
          v37 += 4 * v26 + 516;
          sub_2884(v7, 13, v37);
          continue;
        }
        v15 = 0;
        v16 = ((16 << ((*(_BYTE *)(v6 + (v5 ^ 3)) & 7) + 1)) - 16) | (*(_BYTE *)(v6 + (v5 ^ 3)) << 11) & 0x4000;
        v17 = v7;
        v18 = 0;
      }
LABEL_34:
      sub_23C0(v17, v18, v16, v15);
      ++v5;
      continue;
    }
    if ( v13 != 128 )
    {
      if ( v13 != 144 )
        return result;
      if ( (v10 & 0xF | 2) == 15 )
        return 9;
      sub_2854(v7, v10 & 0xF, &v38);
      v12 = v38;
      goto LABEL_23;
    }
    if ( v9 >= v4 || !((unsigned __int16)((_WORD)v10 << 12) | 16 * *(_BYTE *)(v6 + ((v5 + 1) ^ 3))) )
      return 9;
    sub_23C0(v7, 0, (unsigned __int16)((_WORD)v10 << 12) | 16 * *(_BYTE *)(v6 + (v9 ^ 3)), 0);
    v8 |= (((_WORD)v10 << 12) & 0x8000u) >> 15;
LABEL_55:
    v5 += 2;
  }
  while ( v5 < v4 );
LABEL_57:
  if ( v8 & 1 )
    return 8;
LABEL_58:
  sub_2854(v7, 14, &v36);
  sub_2884(v7, 15, v36);
  return 8;
}

//----- (0000231C) --------------------------------------------------------
signed int __fastcall sub_231C(int a1, int a2, unsigned int a3, int a4, int *a5)
{
  int v5; // r5@1
  int v6; // r4@1
  signed int result; // r0@2
  int v8; // r2@4
  int v9; // r0@4
  int v10; // r1@4
  __int64 v11; // r2@10
  int v12; // r1@10

  v5 = a3;
  v6 = a1;
  switch ( a2 )
  {
    case 0:
      result = 2;
      if ( a3 > 0xF || a4 )
        return result;
      v8 = *a5;
      v9 = v6;
      v10 = v5;
      goto LABEL_14;
    case 1:
      if ( a4 == 5 )
      {
        if ( a3 <= 0x1F )
          goto LABEL_21;
        return 2;
      }
      if ( a4 != 1 || a3 > 0xF )
        return 2;
      sub_2970(a1);
LABEL_21:
      v11 = *(_QWORD *)a5;
      v12 = v5 + 256;
LABEL_22:
      result = sub_28F8(v6, v12, v11, SHIDWORD(v11));
LABEL_23:
      if ( result )
        result = 2;
      return result;
    case 3:
      result = 2;
      if ( a3 > 0x1F || a4 != 5 )
        return result;
      v11 = *(_QWORD *)a5;
      v12 = v5 + 112;
      goto LABEL_22;
    case 4:
      result = 2;
      if ( a3 > 3 || a4 )
        return result;
      v8 = *a5;
      v10 = v5 + 192;
      v9 = v6;
LABEL_14:
      result = sub_2884(v9, v10, v8);
      goto LABEL_23;
    default:
      sub_26F8(
        (int)"_Unwind_VRS_Result _Unwind_VRS_Set(_Unwind_Context *, _Unwind_VRS_RegClass, uint32_t, _Unwind_VRS_DataRepre"
             "sentation, void *)",
        831,
        (int)"unsupported register class");
      return result;
  }
}

//----- (000023C0) --------------------------------------------------------
signed int __fastcall sub_23C0(int a1, int a2, unsigned int a3, int a4)
{
  int v4; // r5@1
  int v5; // r7@1
  unsigned int v6; // r6@1
  int v7; // r8@1
  int v8; // r4@4
  unsigned int v9; // r7@4
  int *v10; // r0@6
  signed int v11; // r0@6
  signed int v12; // r1@6
  signed int v13; // r2@6
  signed int result; // r0@14
  unsigned int v15; // r4@18
  unsigned int v16; // r6@18
  int v17; // r0@19
  int v18; // r2@19
  int v19; // r0@19
  int v20; // r2@22
  int v21; // [sp+8h] [bp-38h]@19
  int v22; // [sp+Ch] [bp-34h]@19
  int v23; // [sp+14h] [bp-2Ch]@16
  int v24; // [sp+18h] [bp-28h]@6
  int *v25; // [sp+1Ch] [bp-24h]@3

  v4 = a2;
  v5 = a4;
  v6 = a3;
  v7 = a1;
  switch ( a2 )
  {
    case 0:
    case 4:
      if ( a4 || sub_2854(a1, 13, &v25) )
        return 2;
      v8 = 0;
      v9 = 0;
      do
      {
        if ( (1 << v9) & v6 )
        {
          v10 = v25;
          ++v25;
          v24 = *v10;
          v11 = sub_231C(v7, v4, v9, 0, &v24);
          v12 = 0;
          v13 = 0;
          if ( v9 == 13 )
            v12 = 1;
          if ( !v4 )
            v13 = 1;
          if ( v11 )
            return 2;
          v8 |= v13 & v12;
        }
        ++v9;
      }
      while ( v9 < 0x10 );
      if ( v8 & 1 )
        return 0;
      v20 = (int)v25;
      goto LABEL_28;
    case 1:
    case 3:
      if ( (a4 | 4) != 5 || sub_2854(a1, 13, &v23) )
        return 2;
      if ( !(_WORD)v6 )
        goto LABEL_21;
      v15 = v6 >> 16;
      v16 = (v6 >> 16) + v6;
      break;
    default:
      sub_26F8(
        (int)"_Unwind_VRS_Result _Unwind_VRS_Pop(_Unwind_Context *, _Unwind_VRS_RegClass, uint32_t, _Unwind_VRS_DataRepresentation)",
        965,
        (int)"unsupported register class");
      return result;
  }
  do
  {
    v17 = v23;
    v23 += 4;
    v18 = *(_DWORD *)v17;
    v23 = v17 + 8;
    v19 = *(_DWORD *)(v17 + 4);
    v21 = v18;
    v22 = v19;
    if ( sub_231C(v7, v4, v15, v5, &v21) )
      return 2;
    ++v15;
  }
  while ( v15 < v16 );
LABEL_21:
  if ( v5 == 1 )
  {
    v20 = v23 + 4;
    v23 += 4;
  }
  else
  {
    v20 = v23;
  }
LABEL_28:
  result = sub_2884(v7, 13, v20);
  if ( result )
    result = 2;
  return result;
}

//----- (000024E4) --------------------------------------------------------
signed int __fastcall sub_24E4(int a1, int a2, int a3)
{
  int v3; // r0@1
  int v4; // r1@1
  unsigned int *v5; // r12@1
  int v6; // r3@1
  unsigned int v7; // r3@4
  unsigned int v8; // r2@4

  v3 = a2;
  v4 = a3;
  v5 = *(unsigned int **)(v3 + 76);
  v6 = (*v5 >> 24) & 0xF;
  if ( v6 )
  {
    if ( v6 != 1 && v6 != 3 )
      return 9;
    v7 = 4 * ((*v5 >> 16) & 0xFF) + 4;
    v8 = 2;
  }
  else
  {
    v8 = 1;
    v7 = 4;
  }
  if ( !v5 || !(*(_BYTE *)(v3 + 80) & 1) && *(unsigned int *)((char *)v5 + v7) )
    return 9;
  return sub_1FD8(v4, (int)v5, v8, v7);
}

//----- (00002538) --------------------------------------------------------
void sub_2538()
{
  JUMPOUT(&loc_24EC);
}

//----- (00002540) --------------------------------------------------------
void sub_2540()
{
  JUMPOUT(&loc_24EC);
}

//----- (000025DC) --------------------------------------------------------
signed int __fastcall sub_25DC(int a1, int a2, char a3)
{
  int v3; // r4@1
  char v4; // r10@1
  signed int i; // r6@1
  signed int v6; // r7@3
  int v7; // r0@8
  int (__fastcall *v8)(signed int, int, char *); // r3@11
  int v9; // r0@12
  int v11; // [sp+0h] [bp-4B0h]@17
  int v12; // [sp+4h] [bp-4ACh]@10
  int (__fastcall *v13)(signed int, int, char *); // [sp+10h] [bp-4A0h]@11
  int v14; // [sp+18h] [bp-498h]@12
  int v15; // [sp+24h] [bp-48Ch]@12
  int v16; // [sp+2Ch] [bp-484h]@10
  char v17; // [sp+30h] [bp-480h]@1

  v3 = a2;
  v4 = a3;
  sub_2804((int)&v17);
  for ( i = 1; ; --i )
  {
    v6 = 1;
    if ( v4 & 1 )
    {
      v6 = 2;
      if ( !i )
      {
        sub_2884((int)&v17, -1, *(_DWORD *)(v3 + 16));
        v4 = 0;
      }
    }
    v7 = sub_2930((int)&v17);
    if ( !v7 )
      break;
    if ( v7 < 0 )
      return 2;
    sub_2854((int)&v17, -2, &v16);
    if ( sub_2938((int)&v17, (int)&v12) )
      return 2;
    v8 = v13;
    if ( v13 )
    {
      *(_DWORD *)(v3 + 72) = v12;
      *(_DWORD *)(v3 + 76) = v15;
      *(_DWORD *)(v3 + 80) = v14;
      v9 = v8(v6, v3, &v17);
      if ( v9 == 7 )
      {
        sub_2854((int)&v17, -1, &v11);
        *(_DWORD *)(v3 + 16) = v11;
        sub_2958((int)&v17);
        return 2;
      }
      if ( v9 == 9 )
        abort();
      if ( v9 != 8 )
        return 2;
      if ( v16 == *(_DWORD *)(v3 + 32) )
        sub_26F8(
          (int)"_Unwind_Reason_Code unwind_phase2(unw_context_t *, _Unwind_Exception *, bool)",
          642,
          (int)"during phase1 personality function said it would stop here, but now in phase2 it did not stop here");
    }
  }
  return 5;
}

//----- (000026F8) --------------------------------------------------------
void __fastcall sub_26F8(int a1, int a2, int a3)
{
  fprintf((FILE *)stderr, "libunwind: %s %s:%d - %s\n", a1, "external/libcxxabi/src/Unwind/Unwind-EHABI.cpp", a2, a3);
  abort();
}

//----- (0000277C) --------------------------------------------------------
int __fastcall sub_277C(int a1, int a2, int a3, int a4, int a5)
{
  int v5; // r4@0
  int v6; // r5@0
  int v7; // r6@0
  int v8; // r7@0
  int v9; // r8@0
  int v10; // r9@0
  int v11; // r10@0
  int v12; // r11@0
  int v13; // r12@0
  int v14; // lr@0

  *(_DWORD *)a1 = a1;
  *(_DWORD *)(a1 + 4) = a2;
  *(_DWORD *)(a1 + 8) = a3;
  *(_DWORD *)(a1 + 12) = a4;
  *(_DWORD *)(a1 + 16) = v5;
  *(_DWORD *)(a1 + 20) = v6;
  *(_DWORD *)(a1 + 24) = v7;
  *(_DWORD *)(a1 + 28) = v8;
  *(_DWORD *)(a1 + 32) = v9;
  *(_DWORD *)(a1 + 36) = v10;
  *(_DWORD *)(a1 + 40) = v11;
  *(_DWORD *)(a1 + 44) = v12;
  *(_DWORD *)(a1 + 48) = v13;
  *(_DWORD *)(a1 + 52) = &a5;
  *(_DWORD *)(a1 + 56) = v14;
  *(_DWORD *)(a1 + 60) = v14;
  return 0;
}

//----- (00002794) --------------------------------------------------------
int __fastcall sub_2794(int _R0)
{
  int result; // r0@1

  __asm { VSTMIA          R0, {D0-D15} }
  return result;
}

//----- (0000279C) --------------------------------------------------------
int __fastcall sub_279C(int _R0)
{
  int result; // r0@1

  __asm { VSTMIA          R0, {D0-D15} }
  return result;
}

//----- (000027A4) --------------------------------------------------------
int __fastcall sub_27A4(int _R0)
{
  int result; // r0@1

  __asm { VSTMIA          R0, {D16-D31} }
  return result;
}

//----- (000027AC) --------------------------------------------------------
void sub_27AC()
{
  __asm
  {
    STCL            p1, c0, [R0],#8
    STCL            p1, c1, [R0],#8
    STCL            p1, c2, [R0],#8
    STCL            p1, c3, [R0],#8
    STCL            p1, c4, [R0],#8
    STCL            p1, c5, [R0],#8
    STCL            p1, c6, [R0],#8
    STCL            p1, c7, [R0],#8
    STCL            p1, c8, [R0],#8
    STCL            p1, c9, [R0],#8
    STCL            p1, c10, [R0],#8
    STCL            p1, c11, [R0],#8
    STCL            p1, c12, [R0],#8
    STCL            p1, c13, [R0],#8
    STCL            p1, c14, [R0],#8
    STCL            p1, c15, [R0],#8
  }
}

//----- (000027F0) --------------------------------------------------------
void sub_27F0()
{
  __asm
  {
    STC2            p1, c8, [R0],#4
    STC2            p1, c9, [R0],#4
    STC2            p1, c10, [R0],#4
    STC2            p1, c11, [R0],#4
  }
}

//----- (00002804) --------------------------------------------------------
int __fastcall sub_2804(int a1)
{
  int v1; // r4@1

  v1 = a1;
  *(_DWORD *)a1 = &off_5D18;
  *(_DWORD *)(a1 + 4) = &unk_611C;
  *(_BYTE *)(a1 + 76) = 0;
  *(_DWORD *)(a1 + 72) = 0;
  _aeabi_memcpy(a1 + 8);
  _aeabi_memset(v1 + 80, 450, 0);
  sub_2D88(v1, 0);
  return 0;
}
// 176C: using guessed type int __fastcall _aeabi_memcpy(_DWORD);
// 1778: using guessed type int __fastcall _aeabi_memset(_DWORD, _DWORD, _DWORD);
// 5D18: using guessed type void *;

//----- (00002854) --------------------------------------------------------
signed int __fastcall sub_2854(int a1, int a2, _DWORD *a3)
{
  int v3; // r6@1
  _DWORD *v4; // r4@1
  int v5; // r5@1
  signed int result; // r0@2

  v3 = a1;
  v4 = a3;
  v5 = a2;
  if ( (*(int (**)(void))(*(_DWORD *)a1 + 8))() == 1 )
  {
    *v4 = (*(int (__fastcall **)(int, int))(*(_DWORD *)v3 + 12))(v3, v5);
    result = 0;
  }
  else
  {
    result = -6542;
  }
  return result;
}

//----- (00002884) --------------------------------------------------------
signed int __fastcall sub_2884(int a1, int a2, int a3)
{
  int v3; // r4@1
  int v4; // r6@1
  int v5; // r5@1
  signed int v6; // r5@3

  v3 = a1;
  v4 = a3;
  v5 = a2;
  if ( (*(int (**)(void))(*(_DWORD *)a1 + 8))() == 1 )
  {
    (*(void (__fastcall **)(int, int, int))(*(_DWORD *)v3 + 16))(v3, v5, v4);
    if ( v5 == -1 )
    {
      v6 = 0;
      (*(void (__fastcall **)(int, _DWORD))(*(_DWORD *)v3 + 52))(v3, 0);
    }
    else
    {
      v6 = 0;
    }
  }
  else
  {
    v6 = -6542;
  }
  return v6;
}

//----- (000028C8) --------------------------------------------------------
signed int __fastcall sub_28C8(int a1, int a2, _QWORD *a3)
{
  int v3; // r6@1
  _QWORD *v4; // r4@1
  int v5; // r5@1
  __int64 v6; // r0@2
  signed int result; // r0@2

  v3 = a1;
  v4 = a3;
  v5 = a2;
  if ( (*(int (**)(void))(*(_DWORD *)a1 + 20))() == 1 )
  {
    LODWORD(v6) = (*(int (__fastcall **)(int, int))(*(_DWORD *)v3 + 24))(v3, v5);
    *v4 = v6;
    result = 0;
  }
  else
  {
    result = -6542;
  }
  return result;
}

//----- (000028F8) --------------------------------------------------------
signed int __fastcall sub_28F8(int a1, int a2, int a3, int a4)
{
  int v4; // r7@1
  int v5; // r5@1
  int v6; // r6@1
  int v7; // r8@1
  signed int result; // r0@2

  v4 = a1;
  v5 = a3;
  v6 = a2;
  v7 = a4;
  if ( (*(int (**)(void))(*(_DWORD *)a1 + 20))() == 1 )
  {
    (*(void (__fastcall **)(int, int, int, int))(*(_DWORD *)v4 + 28))(v4, v6, v5, v7);
    result = 0;
  }
  else
  {
    result = -6542;
  }
  return result;
}

//----- (00002930) --------------------------------------------------------
int __fastcall sub_2930(int a1)
{
  return (*(int (**)(void))(*(_DWORD *)a1 + 32))();
}

//----- (00002938) --------------------------------------------------------
signed int __fastcall sub_2938(int a1, int a2)
{
  int v2; // r4@1
  signed int result; // r0@1

  v2 = a2;
  (*(void (**)(void))(*(_DWORD *)a1 + 36))();
  result = 0;
  if ( !*(_DWORD *)(v2 + 4) )
    result = -6549;
  return result;
}

//----- (00002958) --------------------------------------------------------
signed int __fastcall sub_2958(int a1)
{
  (*(void (**)(void))(*(_DWORD *)a1 + 40))();
  return -6540;
}

//----- (00002970) --------------------------------------------------------
int __fastcall sub_2970(int a1)
{
  return (*(int (**)(void))(*(_DWORD *)a1 + 60))();
}

//----- (00002980) --------------------------------------------------------
int __fastcall sub_2980(int a1, int a2)
{
  signed int v2; // r2@1
  bool v3; // zf@1
  signed int v4; // r0@1
  unsigned int v5; // r1@1

  v2 = 0;
  v3 = (a2 & 0xFFFFFFFC) == 192;
  v4 = 0;
  v5 = a2 - 16;
  if ( v3 )
    v4 = 1;
  if ( v5 > 0xFFFFFFED )
    v2 = 1;
  return v4 | v2;
}

//----- (000029A4) --------------------------------------------------------
int __fastcall sub_29A4(int a1, signed int a2)
{
  signed int v2; // r5@1
  int v3; // r4@1
  int v4; // r0@7

  v2 = a2;
  v3 = a1;
  if ( a2 >= -1 )
  {
    if ( a2 > 13 )
    {
      if ( a2 == 14 )
      {
        v4 = a1 + 64;
        return *(_DWORD *)v4;
      }
      if ( a2 != 15 )
        goto LABEL_12;
    }
    else if ( a2 != -1 )
    {
      if ( a2 != 13 )
        goto LABEL_12;
LABEL_7:
      v4 = a1 + 60;
      return *(_DWORD *)v4;
    }
    v4 = a1 + 68;
    return *(_DWORD *)v4;
  }
  if ( a2 == -2 )
    goto LABEL_7;
LABEL_12:
  if ( (unsigned int)a2 > 0xC )
  {
    if ( (a2 & 0xFFFFFFFC) != 192 )
      sub_2DE4(
        (int)"uint32_t libunwind::Registers_arm::getRegister(int)",
        (int)"external/libcxxabi/src/Unwind/Registers.hpp",
        1452,
        (int)"unsupported arm register");
    if ( !*(_BYTE *)(a1 + 76) )
    {
      *(_BYTE *)(a1 + 76) = 1;
      sub_27F0();
    }
    v4 = v3 + 4 * v2 - 296;
  }
  else
  {
    v4 = a1 + 4 * a2 + 8;
  }
  return *(_DWORD *)v4;
}

//----- (00002A40) --------------------------------------------------------
int __fastcall sub_2A40(int result, signed int a2, int a3)
{
  signed int v3; // r6@1
  int v4; // r4@1
  int v5; // r5@1

  v3 = a2;
  v4 = a3;
  v5 = result;
  if ( a2 >= -1 )
  {
    if ( a2 > 13 )
    {
      if ( a2 == 14 )
      {
        *(_DWORD *)(result + 64) = a3;
        return result;
      }
      if ( a2 != 15 )
        goto LABEL_12;
    }
    else if ( a2 != -1 )
    {
      if ( a2 != 13 )
        goto LABEL_12;
LABEL_7:
      *(_DWORD *)(result + 60) = a3;
      return result;
    }
    *(_DWORD *)(result + 68) = a3;
    return result;
  }
  if ( a2 == -2 )
    goto LABEL_7;
LABEL_12:
  if ( (unsigned int)a2 > 0xC )
  {
    if ( (a2 & 0xFFFFFFFC) != 192 )
      sub_2DE4(
        (int)"void libunwind::Registers_arm::setRegister(int, uint32_t)",
        (int)"external/libcxxabi/src/Unwind/Registers.hpp",
        1471,
        (int)"unsupported arm register");
    if ( !*(_BYTE *)(result + 76) )
    {
      *(_BYTE *)(result + 76) = 1;
      sub_27F0();
    }
    result = v5 + 4 * v3;
    *(_DWORD *)(result - 296) = v4;
  }
  else
  {
    result += 4 * a2;
    *(_DWORD *)(result + 8) = a3;
  }
  return result;
}

//----- (00002AD8) --------------------------------------------------------
int __fastcall sub_2AD8(int a1, int a2)
{
  signed int v2; // r2@1
  bool v3; // zf@1
  signed int v4; // r0@1
  unsigned int v5; // r1@1

  v2 = 0;
  v3 = (a2 & 0xFFFFFFF0) == 112;
  v4 = 0;
  v5 = a2 & 0xFFFFFFE0;
  if ( v3 )
    v4 = 1;
  if ( v5 == 256 )
    v2 = 1;
  return v4 | v2;
}

//----- (00002AFC) --------------------------------------------------------
__int64 __fastcall sub_2AFC(int a1, int a2)
{
  int v2; // r4@1
  int v3; // r5@1
  unsigned int v4; // r0@1
  int v5; // r0@5
  int v6; // r0@11

  v2 = a2;
  v3 = a1;
  v4 = a2 & 0xFFFFFFF0;
  if ( (a2 & 0xFFFFFFF0) == 112 )
  {
    if ( !*(_BYTE *)(v3 + 75) )
    {
      *(_BYTE *)(v3 + 75) = 1;
      sub_27AC();
    }
    v5 = v3 + 8 * v2 - 552;
  }
  else if ( v4 == 272 )
  {
    if ( !*(_BYTE *)(v3 + 74) )
    {
      *(_BYTE *)(v3 + 74) = 1;
      sub_27A4(v3 + 216);
    }
    v5 = v3 + 8 * v2 - 1960;
  }
  else
  {
    if ( v4 != 256 )
      sub_2DE4(
        (int)"unw_fpreg_t libunwind::Registers_arm::getFloatRegister(int)",
        (int)"external/libcxxabi/src/Unwind/Registers.hpp",
        1673,
        (int)"Unknown ARM float register");
    if ( !*(_BYTE *)(v3 + 73) )
    {
      *(_BYTE *)(v3 + 73) = 1;
      v6 = v3 + 80;
      if ( *(_BYTE *)(v3 + 72) )
        sub_279C(v6);
      else
        sub_2794(v6);
    }
    v5 = v3 + 8 * v2 - 1968;
  }
  return *(_QWORD *)v5;
}

//----- (00002BAC) --------------------------------------------------------
int __fastcall sub_2BAC(int a1, int a2, int a3, int a4)
{
  int v4; // r6@1
  int v5; // r7@1
  unsigned int v6; // r0@1
  int v7; // r5@1
  int v8; // r4@1
  int result; // r0@5
  int v10; // r1@5
  int v11; // r0@11

  v4 = a2;
  v5 = a1;
  v6 = a2 & 0xFFFFFFF0;
  v7 = a4;
  v8 = a3;
  if ( (a2 & 0xFFFFFFF0) == 112 )
  {
    if ( !*(_BYTE *)(v5 + 75) )
    {
      *(_BYTE *)(v5 + 75) = 1;
      sub_27AC();
    }
    result = v5 + 8 * v4;
    *(_DWORD *)(result - 548) = v7;
    LOWORD(v10) = -552;
  }
  else if ( v6 == 272 )
  {
    if ( !*(_BYTE *)(v5 + 74) )
    {
      *(_BYTE *)(v5 + 74) = 1;
      sub_27A4(v5 + 216);
    }
    result = v5 + 8 * v4;
    *(_DWORD *)(result - 1828) = v7;
    LOWORD(v10) = -1832;
  }
  else
  {
    if ( v6 != 256 )
      sub_2DE4(
        (int)"void libunwind::Registers_arm::setFloatRegister(int, unw_fpreg_t)",
        (int)"external/libcxxabi/src/Unwind/Registers.hpp",
        1700,
        (int)"Unknown ARM float register");
    if ( !*(_BYTE *)(v5 + 73) )
    {
      *(_BYTE *)(v5 + 73) = 1;
      v11 = v5 + 80;
      if ( *(_BYTE *)(v5 + 72) )
        sub_279C(v11);
      else
        sub_2794(v11);
    }
    result = v5 + 8 * v4;
    *(_DWORD *)(result - 1964) = v7;
    LOWORD(v10) = -1968;
  }
  HIWORD(v10) = -1;
  *(_DWORD *)(result + v10) = v8;
  return result;
}

//----- (00002C80) --------------------------------------------------------
signed int __fastcall sub_2C80(int a1)
{
  int v1; // r4@1
  signed int result; // r0@3
  void (__fastcall *v3)(int, signed int, int); // r5@5
  int v4; // r0@5

  v1 = a1;
  if ( *(_BYTE *)(a1 + 528)
    || ((*(void (__fastcall **)(int, signed int))(*(_DWORD *)a1 + 52))(a1, 1), *(_BYTE *)(v1 + 528)) )
  {
    result = 0;
  }
  else
  {
    if ( *(_DWORD *)(v1 + 504) )
    {
      v3 = *(void (__fastcall **)(int, signed int, int))(*(_DWORD *)v1 + 16);
      v4 = (*(int (__fastcall **)(int, signed int))(*(_DWORD *)v1 + 12))(v1, -2);
      v3(v1, -2, *(_DWORD *)(v1 + 504) + v4);
    }
    result = 1;
  }
  return result;
}

//----- (00002CCC) --------------------------------------------------------
int __fastcall sub_2CCC(int a1, int a2)
{
  int v2; // r3@1
  int v3; // r4@1
  int v4; // r5@1
  int v5; // r12@1
  int v6; // lr@1
  int v7; // r4@1
  int v8; // r2@1
  int v9; // r3@1
  int v10; // r5@1
  int result; // r0@1

  v2 = *(_DWORD *)(a1 + 504);
  v3 = *(_DWORD *)(a1 + 496);
  v4 = *(_DWORD *)(a1 + 500);
  v5 = *(_DWORD *)(a1 + 488);
  v6 = *(_DWORD *)(a1 + 492);
  *(_DWORD *)(a2 + 20) = *(_DWORD *)(a1 + 508);
  *(_DWORD *)(a2 + 16) = v2;
  *(_DWORD *)(a2 + 12) = v4;
  *(_DWORD *)(a2 + 8) = v3;
  v7 = a2 + 24;
  *(_DWORD *)a2 = v5;
  *(_DWORD *)(a2 + 4) = v6;
  v8 = *(_DWORD *)(a1 + 512);
  v9 = *(_DWORD *)(a1 + 516);
  v10 = *(_DWORD *)(a1 + 520);
  result = *(_DWORD *)(a1 + 524);
  *(_DWORD *)(a2 + 36) = result;
  *(_DWORD *)v7 = v8;
  *(_DWORD *)(v7 + 4) = v9;
  *(_DWORD *)(v7 + 8) = v10;
  return result;
}

//----- (00002D0C) --------------------------------------------------------
void __fastcall sub_2D0C(int a1)
{
  sub_2E18(a1 + 8);
  sub_3784();
}

//----- (00002D24) --------------------------------------------------------
int __fastcall sub_2D24(int a1)
{
  return *(_BYTE *)(a1 + 529);
}

//----- (00002D2C) --------------------------------------------------------
signed int __fastcall sub_2D2C(int a1, int a2, int a3, _DWORD *a4)
{
  int v4; // r6@1
  int v5; // r5@1
  _DWORD *v6; // r4@1
  int v7; // r7@1
  signed int result; // r0@3
  int v9; // [sp+10h] [bp-20h]@2
  int v10; // [sp+14h] [bp-1Ch]@3

  v4 = a2;
  v5 = a3;
  v6 = a4;
  v7 = (*(int (**)(void))(*(_DWORD *)a1 + 12))();
  if ( dladdr() && v9 )
  {
    _snprintf_chk(v4, v5, 0, -1);
    *v6 = v7 - v10;
    result = 1;
  }
  else
  {
    result = 0;
  }
  return result;
}
// 1784: using guessed type int dladdr(void);
// 1790: using guessed type int __fastcall _snprintf_chk(_DWORD, _DWORD, _DWORD, _DWORD);

//----- (00002D88) --------------------------------------------------------
int __fastcall sub_2D88(int a1, int a2)
{
  int v2; // r4@1
  int v3; // r6@1
  unsigned int v4; // r5@1
  int result; // r0@5
  int v6; // [sp+4h] [bp-1Ch]@3
  int v7; // [sp+8h] [bp-18h]@3
  int v8; // [sp+Ch] [bp-14h]@1

  v2 = a1;
  v3 = a2;
  v4 = (*(int (**)(void))(*(_DWORD *)a1 + 12))() & 0xFFFFFFFE;
  v8 = 0;
  if ( v3 )
    --v4;
  v6 = _gnu_Unwind_Find_exidx(v4, &v8);
  v7 = v8;
  if ( !v6 || !v8 || (result = ((int (__fastcall *)(int, unsigned int, int *))sub_2E68)(v2, v4, &v6)) == 0 )
  {
    result = 1;
    *(_BYTE *)(v2 + 528) = 1;
  }
  return result;
}
// 179C: using guessed type int __fastcall _gnu_Unwind_Find_exidx(_DWORD, _DWORD);
// 2E68: using guessed type int sub_2E68();

//----- (00002DD4) --------------------------------------------------------
const char *__fastcall sub_2DD4(int a1, signed int a2)
{
  const char *result; // r0@2
  signed int v3; // r0@3
  int *v4; // r1@3

  if ( a2 > 255 )
  {
    switch ( a2 )
    {
      case 256:
        v3 = -7163;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 257:
        v3 = -7160;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 258:
        v3 = -7157;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 259:
        v3 = -7154;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 260:
        v3 = -7151;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 261:
        v3 = -7148;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 262:
        v3 = -7145;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 263:
        v3 = -7142;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 264:
        v3 = -7139;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 265:
        v3 = -7136;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 266:
        v3 = -7133;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 267:
        v3 = -7129;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 268:
        v3 = -7125;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 269:
        v3 = -7121;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 270:
        v3 = -7117;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 271:
        v3 = -7113;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 272:
        v3 = -7109;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 273:
        v3 = -7105;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 274:
        v3 = -7101;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 275:
        v3 = -7097;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 276:
        v3 = -7093;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 277:
        v3 = -7089;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 278:
        v3 = -7085;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 279:
        v3 = -7081;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 280:
        v3 = -7077;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 281:
        v3 = -7073;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 282:
        v3 = -7069;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 283:
        v3 = -7065;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 284:
        v3 = -7061;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 285:
        v3 = -7057;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 286:
        v3 = -7053;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 287:
        v3 = -7049;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      default:
def_3144:
        v3 = -7045;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
    }
  }
  else
  {
    result = "pc";
    switch ( a2 + 2 )
    {
      case 0:
      case 15:
        v3 = -7326;
        v4 = &GLOBAL_OFFSET_TABLE_;
        return (char *)v4 + v3;
      default:
        goto def_3144;
      case 1:
      case 17:
        return result;
      case 2:
        v3 = -7323;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 3:
        v3 = -7320;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 4:
        v3 = -7317;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 5:
        v3 = -7314;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 6:
        v3 = -7311;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 7:
        v3 = -7308;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 8:
        v3 = -7305;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 9:
        v3 = -7302;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 10:
        v3 = -7299;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 11:
        v3 = -7296;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 12:
        v3 = -7293;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 13:
        v3 = -7289;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 14:
        v3 = -7285;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 16:
        v3 = -7329;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 66:
        v3 = -7281;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 67:
        v3 = -7278;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 68:
        v3 = -7275;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 69:
        v3 = -7272;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 70:
        v3 = -7269;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 71:
        v3 = -7266;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 72:
        v3 = -7263;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 73:
        v3 = -7260;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 74:
        v3 = -7257;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 75:
        v3 = -7254;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 76:
        v3 = -7251;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 77:
        v3 = -7247;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 78:
        v3 = -7243;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 79:
        v3 = -7239;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 80:
        v3 = -7235;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 81:
        v3 = -7231;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 82:
        v3 = -7227;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 83:
        v3 = -7223;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 84:
        v3 = -7219;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 85:
        v3 = -7215;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 86:
        v3 = -7211;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 87:
        v3 = -7207;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 88:
        v3 = -7203;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 89:
        v3 = -7199;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 90:
        v3 = -7195;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 91:
        v3 = -7191;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 92:
        v3 = -7187;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 93:
        v3 = -7183;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 94:
        v3 = -7179;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 95:
        v3 = -7175;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 96:
        v3 = -7171;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 97:
        v3 = -7167;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
    }
  }
  return (char *)v4 + v3;
}
// 5F00: using guessed type int GLOBAL_OFFSET_TABLE_;

//----- (00002DDC) --------------------------------------------------------
int __fastcall sub_2DDC(int result)
{
  *(_BYTE *)(result + 72) = 1;
  return result;
}

//----- (00002DE4) --------------------------------------------------------
void __fastcall sub_2DE4(int a1, int a2, int a3, int a4)
{
  fprintf((FILE *)stderr, "libunwind: %s %s:%d - %s\n", a1, a2, a3, a4);
  abort();
}

//----- (00002E18) --------------------------------------------------------
int __fastcall sub_2E18(int a1)
{
  int v1; // r4@1
  int v2; // r0@2
  int result; // r0@9

  v1 = a1;
  if ( *(_BYTE *)(a1 + 65) )
  {
    v2 = a1 + 72;
    if ( *(_BYTE *)(v1 + 64) )
      sub_36EC(v2);
    else
      sub_36E4(v2);
  }
  if ( *(_BYTE *)(v1 + 66) )
    sub_36F4(v1 + 208);
  if ( *(_BYTE *)(v1 + 67) )
    sub_36FC((_DWORD *)(v1 + 336));
  result = *(_BYTE *)(v1 + 68);
  if ( *(_BYTE *)(v1 + 68) )
    result = sub_3794((_DWORD *)(v1 + 464));
  return result;
}

//----- (00002FF8) --------------------------------------------------------
int __fastcall sub_2FF8(int result, int a2, int a3, _DWORD *a4, int a5, int a6, int a7, _DWORD *a8)
{
  unsigned int v8; // r4@1
  unsigned int v9; // r5@2
  int v10; // r6@3

  v8 = a5 - a2;
  while ( 1 )
  {
    v9 = v8;
    if ( !v8 )
      break;
    v10 = a2 + (v8 >> 1);
    v8 >>= 1;
    if ( *a8 >= *a4 + 8 * v10 + (2 * *(_DWORD *)(*a4 + 8 * v10) & 0x80000000 | *(_DWORD *)(*a4 + 8 * v10)) )
    {
      v8 = v9 - 1 - v8;
      a2 = v10 + 1;
    }
  }
  *(_DWORD *)result = a2;
  *(_DWORD *)(result + 4) = a3;
  *(_DWORD *)(result + 8) = a4;
  return result;
}

//----- (000036E4) --------------------------------------------------------
int __fastcall sub_36E4(int _R0)
{
  int result; // r0@1

  __asm { VLDMIA          R0, {D0-D15} }
  return result;
}

//----- (000036EC) --------------------------------------------------------
int __fastcall sub_36EC(int _R0)
{
  int result; // r0@1

  __asm { VLDMIA          R0, {D0-D15} }
  return result;
}

//----- (000036F4) --------------------------------------------------------
int __fastcall sub_36F4(int _R0)
{
  int result; // r0@1

  __asm { VLDMIA          R0, {D16-D31} }
  return result;
}

//----- (000036FC) --------------------------------------------------------
int __fastcall sub_36FC(_DWORD *a1)
{
  int *v5; // r0@1
  int result; // r0@1

  _T1 = *a1;
  v5 = a1 + 2;
  __asm { LDCL            p1, c0, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c1, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c2, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c3, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c4, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c5, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c6, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c7, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c8, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c9, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c10, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c11, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c12, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c13, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c14, [R0],#8 }
  _T1 = *v5;
  result = (int)(v5 + 2);
  __asm { LDCL            p1, c15, [R0],#8 }
  return result;
}

//----- (00003740) --------------------------------------------------------
int __fastcall sub_3740(_DWORD *a1)
{
  int *v5; // r0@1
  int result; // r0@1

  _T1 = *a1;
  v5 = a1 + 1;
  __asm { LDC2            p1, c8, [R0],#4 }
  _T1 = *v5;
  ++v5;
  __asm { LDC2            p1, c9, [R0],#4 }
  _T1 = *v5;
  ++v5;
  __asm { LDC2            p1, c10, [R0],#4 }
  _T1 = *v5;
  result = (int)(v5 + 1);
  __asm { LDC2            p1, c11, [R0],#4 }
  return result;
}

//----- (00003784) --------------------------------------------------------
void sub_3784()
{
  sub_3788();
}

//----- (00003788) --------------------------------------------------------
void sub_3788()
{
  JUMPOUT(sub_36D0);
}
// 36D0: using guessed type int sub_36D0();

//----- (00003794) --------------------------------------------------------
int __fastcall sub_3794(_DWORD *a1)
{
  return sub_3798(a1);
}

//----- (00003798) --------------------------------------------------------
int __fastcall sub_3798(_DWORD *a1)
{
  return sub_3740(a1);
}

// ALL OK, 107 function(s) have been successfully decompiled
