/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'hwcomposer.hi6210sft'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

/* 1 */
struct timezone
{
  int tz_minuteswest;
  int tz_dsttime;
};

/* 4 */
typedef unsigned __int64 __u_quad_t;

/* 3 */
typedef __u_quad_t __dev_t;

/* 5 */
typedef unsigned __int32 __ino_t;

/* 6 */
typedef unsigned int __mode_t;

/* 7 */
typedef unsigned int __nlink_t;

/* 8 */
typedef unsigned int __uid_t;

/* 9 */
typedef unsigned int __gid_t;

/* 10 */
typedef __int32 __off_t;

/* 11 */
typedef __int32 __blksize_t;

/* 12 */
typedef __int32 __blkcnt_t;

/* 14 */
typedef __int32 __time_t;

/* 13 */
struct timespec
{
  __time_t tv_sec;
  __int32 tv_nsec;
};

/* 2 */
struct stat
{
  __dev_t st_dev;
  unsigned __int16 __pad1;
  __ino_t st_ino;
  __mode_t st_mode;
  __nlink_t st_nlink;
  __uid_t st_uid;
  __gid_t st_gid;
  __dev_t st_rdev;
  unsigned __int16 __pad2;
  __off_t st_size;
  __blksize_t st_blksize;
  __blkcnt_t st_blocks;
  timespec st_atim;
  timespec st_mtim;
  timespec st_ctim;
  unsigned __int32 __unused4;
  unsigned __int32 __unused5;
};

/* 15 */
struct HwcConfig;

/* 16 */
struct HwcIdleMgr;

/* 17 */
struct HwcBandwidth;

/* 18 */
struct HwcDisplay;

/* 19 */
struct Hi62xxAccelerator;

/* 20 */
struct HwcCompInfo;

/* 21 */
struct HwcPartialUpdates;

/* 22 */
struct ChannelMgr;

/* 23 */
struct HwcLayerInfo;

/* 24 */
struct HwcMem;

/* 25 */
struct IAccelerator;

/* 26 */
struct Hi62xxPlatform;

/* 27 */
struct Hi363xPlatform;

/* 28 */
struct Channel;

/* 29 */
struct HwcPureLayerChecker;

/* 30 */
struct PrimaryOnlinePolicy;

/* 31 */
struct OfflinePolicy;

/* 32 */
struct GpuComposePolicy;

/* 33 */
struct IdleGpuComposePolicy;

/* 34 */
struct VirtualDisplayPolicy;

/* 35 */
struct VirtualDisplaySkipPolicy;

/* 36 */
struct PartialUpdatesResetPolicy;

/* 37 */
struct CapaProvider;

/* 38 */
struct IdlePolicy;

/* 39 */
struct BlockRotPolicy;

/* 40 */
struct tinyxml2::XMLElement;

/* 41 */
struct tinyxml2::XMLAttribute;

/* 42 */
struct tinyxml2::XMLDocument;

/* 43 */
struct tinyxml2::XMLNode;

/* 44 */
struct PureLayerPolicy;

/* 45 */
struct Hi62xxRot;

/* 46 */
struct Hi62xxScl3;

/* 47 */
struct Hi62xxScl2;

/* 48 */
struct android::VectorImpl;

/* 49 */
struct Hi62xxCommon;

/* 50 */
struct Hi62xxOverlay;

/* 51 */
struct Hi62xxComposer;

/* 52 */
struct Hi62XXPerf;

/* 53 */
struct Segmenter;

/* 54 */
struct Hi363xAccelerator;

/* 55 */
struct Hi363xOverlay;

/* 56 */
struct Hi363xComposer;

/* 57 */
struct Hi363xPerf;

/* 58 */
struct IdleBoostPolicy;

/* 59 */
struct VirtualDisplayGpuPolicy;

/* 60 */
struct tinyxml2::StrPair;

/* 61 */
struct tinyxml2::XMLUtil;

/* 62 */
struct tinyxml2::XMLComment;

/* 63 */
struct tinyxml2::XMLDeclaration;

/* 64 */
struct tinyxml2::XMLUnknown;

/* 65 */
struct tinyxml2::XMLPrinter;

/* 66 */
struct tinyxml2::XMLText;

/* 68 */
typedef __int32 __suseconds_t;

/* 67 */
struct timeval
{
  __time_t tv_sec;
  __suseconds_t tv_usec;
};

