/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2015 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

// int __fastcall _cxa_finalize(_DWORD); weak
signed int __fastcall j_hw_set_colortemperature(int _R0);
signed int __fastcall j_hw_update_rgb_gamma(int a1, int _R1, int _R2);
int __fastcall j_hw_set_comfort_mode(unsigned int a1);
int __fastcall j_hw_get_smart_display_supported(_DWORD *a1);
int j_hw_update_color_temp_for_rg_led();
signed int j_hw_set_color_mode();
// int open(const char *file, int oflag, ...);
// int _android_log_print(_DWORD, _DWORD, const char *, ...); weak
// int _sprintf_chk(_DWORD, _DWORD, _DWORD, const char *, ...); weak
// ssize_t write(int fd, const void *buf, size_t n);
// int close(int fd);
// int __fastcall _stack_chk_fail(_DWORD); weak
// int __cdecl _errno(_DWORD); weak
// void abort(void);
// int fprintf(FILE *stream, const char *format, ...);
// int __fastcall _aeabi_memcpy(_DWORD); weak
// int __fastcall _aeabi_memset(_DWORD, _DWORD, _DWORD); weak
// int dladdr(void); weak
// int __fastcall _snprintf_chk(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int __fastcall _gnu_Unwind_Find_exidx(_DWORD, _DWORD); weak
int sub_A0C();
int (*__fastcall sub_A2C(int (*result)(void)))(void);
signed int hw_set_color_mode();
int sub_B0A();
signed int __fastcall hw_set_colortemperature(int _R0);
signed int __fastcall hw_update_rgb_gamma(int a1, int _R1, int _R2);
int __fastcall hw_set_comfort_mode(unsigned int a1);
int __fastcall hw_get_smart_display_supported(_DWORD *a1);
int hw_update_color_temp_for_rg_led();
signed int __fastcall sub_F14(int a1, int a2, unsigned int a3, unsigned int a4);
signed int __fastcall sub_1258(int a1, int a2, unsigned int a3, int a4, int *a5);
signed int __fastcall sub_12FC(int a1, int a2, unsigned int a3, int a4);
signed int __fastcall sub_1420(int a1, int a2, int a3);
void sub_1474();
void sub_147C();
signed int __fastcall sub_1518(int a1, int a2, char a3);
void __fastcall sub_1634(int a1, int a2, int a3);
int __fastcall sub_16B8(int a1, int a2, int a3, int a4, int a5);
int __fastcall sub_16D0(int _R0);
int __fastcall sub_16D8(int _R0);
int __fastcall sub_16E0(int _R0);
void sub_16E8();
void sub_172C();
int __fastcall sub_1740(int a1);
signed int __fastcall sub_1790(int a1, int a2, _DWORD *a3);
signed int __fastcall sub_17C0(int a1, int a2, int a3);
signed int __fastcall sub_1804(int a1, int a2, _QWORD *a3);
signed int __fastcall sub_1834(int a1, int a2, int a3, int a4);
int __fastcall sub_186C(int a1);
signed int __fastcall sub_1874(int a1, int a2);
signed int __fastcall sub_1894(int a1);
int __fastcall sub_18AC(int a1);
int __fastcall sub_18BC(int a1, int a2);
int __fastcall sub_18E0(int a1, signed int a2);
int __fastcall sub_197C(int result, signed int a2, int a3);
int __fastcall sub_1A14(int a1, int a2);
__int64 __fastcall sub_1A38(int a1, int a2);
int __fastcall sub_1AE8(int a1, int a2, int a3, int a4);
signed int __fastcall sub_1BBC(int a1);
int __fastcall sub_1C08(int a1, int a2);
void __fastcall sub_1C48(int a1);
int __fastcall sub_1C60(int a1);
signed int __fastcall sub_1C68(int a1, int a2, int a3, _DWORD *a4);
int __fastcall sub_1CC4(int a1, int a2);
const char *__fastcall sub_1D10(int a1, signed int a2);
int __fastcall sub_1D18(int result);
void __fastcall sub_1D20(int a1, int a2, int a3, int a4);
int __fastcall sub_1D54(int a1);
int sub_1DA4(); // weak
int __fastcall sub_1F34(int result, int a2, int a3, _DWORD *a4, int a5, int a6, int a7, _DWORD *a8);
int sub_260C(); // weak
int __fastcall sub_2620(int _R0);
int __fastcall sub_2628(int _R0);
int __fastcall sub_2630(int _R0);
int __fastcall sub_2638(_DWORD *a1);
int __fastcall sub_267C(_DWORD *a1);
signed int __fastcall j_j_j_hw_set_colortemperature(int _R0);
signed int __fastcall j_j_hw_set_colortemperature(int _R0);
signed int __fastcall j_j_j_hw_update_rgb_gamma(int a1, int _R1, int _R2);
signed int __fastcall j_j_hw_update_rgb_gamma(int a1, int _R1, int _R2);
int __fastcall j_j_j_hw_set_comfort_mode(unsigned int a1);
int __fastcall j_j_hw_set_comfort_mode(unsigned int a1);
int __fastcall j_j_j_hw_get_smart_display_supported(_DWORD *a1);
int __fastcall j_j_hw_get_smart_display_supported(_DWORD *a1);
int j_j_j_hw_update_color_temp_for_rg_led();
int j_j_hw_update_color_temp_for_rg_led();
signed int j_j_j_hw_set_color_mode();
signed int j_j_hw_set_color_mode();
void sub_26F0();
void sub_26F4();
int __fastcall sub_2700(_DWORD *a1);
int __fastcall sub_2704(_DWORD *a1);

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN loc_1428; // weak
void *off_4E20 = (void *)0x18B5; // weak
int GLOBAL_OFFSET_TABLE_ = 0; // weak
void *off_5000 = &off_5000; // weak
int dword_5004; // weak
_UNKNOWN unk_5008; // weak
// extern _UNKNOWN _stack_chk_guard; weak
// extern struct _IO_FILE *stderr;


//----- (0000091C) --------------------------------------------------------
signed int __fastcall j_hw_set_colortemperature(int _R0)
{
  return hw_set_colortemperature(_R0);
}

//----- (00000928) --------------------------------------------------------
signed int __fastcall j_hw_update_rgb_gamma(int a1, int _R1, int _R2)
{
  return hw_update_rgb_gamma(a1, _R1, _R2);
}

//----- (00000934) --------------------------------------------------------
int __fastcall j_hw_set_comfort_mode(unsigned int a1)
{
  return hw_set_comfort_mode(a1);
}

//----- (00000940) --------------------------------------------------------
int __fastcall j_hw_get_smart_display_supported(_DWORD *a1)
{
  return hw_get_smart_display_supported(a1);
}

//----- (0000094C) --------------------------------------------------------
int j_hw_update_color_temp_for_rg_led()
{
  return hw_update_color_temp_for_rg_led();
}

//----- (00000958) --------------------------------------------------------
signed int j_hw_set_color_mode()
{
  return hw_set_color_mode();
}

//----- (00000A0C) --------------------------------------------------------
int sub_A0C()
{
  return _cxa_finalize(&off_5000);
}
// 8F8: using guessed type int __fastcall _cxa_finalize(_DWORD);
// 5000: using guessed type void *off_5000;

//----- (00000A2C) --------------------------------------------------------
int (*__fastcall sub_A2C(int (*result)(void)))(void)
{
  if ( result )
    result = (int (*)(void))result();
  return result;
}

//----- (00000B04) --------------------------------------------------------
signed int hw_set_color_mode()
{
  return -1;
}

//----- (00000B0A) --------------------------------------------------------
int sub_B0A()
{
  signed int v4; // r2@1
  int v5; // r1@1
  int v7; // r3@1

  __asm
  {
    VCVTR.S32.F32   S15, S0
    VMOV.F32        S1, #1.0
  }
  v4 = 1;
  v5 = 0;
  __asm
  {
    VCVT.F32.U32    S14, S15
    VMOV            R3, S15
    VSUB.F32        S0, S0, S14
  }
  v7 = (_R3 & 0xF) << 8;
  while ( 1 )
  {
    __asm { VADD.F32        S0, S0, S0 }
    if ( !_ZF )
      break;
    __asm
    {
      VCMPE.F32       S0, S1
      VMRS            APSR_nzcv, FPSCR
    }
    if ( !(_NF ^ _VF) )
      goto LABEL_4;
LABEL_6:
    ++v4;
  }
  __asm { VCMPE.F32       S0, S1 }
  v5 *= 2;
  __asm { VMRS            APSR_nzcv, FPSCR }
  if ( _NF ^ _VF )
    goto LABEL_5;
LABEL_4:
  __asm { VSUB.F32        S0, S0, S1 }
  v5 |= 1u;
LABEL_5:
  if ( v4 != 8 )
    goto LABEL_6;
  return v5 & 0x7FFF | v7;
}

//----- (00000B60) --------------------------------------------------------
signed int __fastcall hw_set_colortemperature(int _R0)
{
  int v5; // r7@1
  signed int result; // r0@2
  unsigned int v8; // r4@6
  int v9; // r1@6
  int v10; // r5@7
  ssize_t v11; // r11@16
  int v12; // [sp+14h] [bp-C4h]@9
  int v13[4]; // [sp+1Ch] [bp-BCh]@12
  int v14; // [sp+2Ch] [bp-ACh]@16
  int v15; // [sp+3Ch] [bp-9Ch]@16
  char v16; // [sp+40h] [bp-98h]@16
  int v17; // [sp+A4h] [bp-34h]@1

  __asm { VMOV            S16, R0 }
  v17 = _stack_chk_guard;
  v5 = open("/sys/class/graphics/fb0/lcd_color_temperature", 2);
  if ( v5 >= 0 )
  {
    __asm
    {
      VMOV            R0, S16
      VMOV.F32        S13, #1.0
      VLDR            S14, =128.0
      VLDR            S12, =0.0078125
    }
    if ( _R0 <= 0x7F )
    {
      __asm
      {
        VCVT.F32.S32    S0, S16
        VLDR            S15, =0.1
        VMOV.F32        S17, S13
        VMOV.F32        S16, S13
        VSUB.F32        S1, S14, S0
        VMUL.F32        S2, S1, S12
        VMLS.F32        S17, S2, S15
      }
    }
    else
    {
      __asm
      {
        VCVT.F32.U32    S3, S16
        VLDR            S6, =0.05
        VMOV.F32        S7, S13
        VMOV.F32        S17, S13
        VSUB.F32        S4, S3, S14
        VMUL.F32        S5, S4, S12
        VMLS.F32        S7, S5, S6
        VMOV.F32        S16, S7
      }
    }
    v8 = 0;
    v9 = 0;
    do
    {
      v10 = 0;
      do
      {
        if ( v8 == v10 )
        {
          v12 = v9;
          if ( v8 > 1 )
            __asm { VMOVHI.F32      S0, S17 }
          else
            __asm { VMOVLS.F32      S0, S16 }
          v13[4 * v8] = sub_B0A();
          v9 = v12;
        }
        else
        {
          *(&v13[3 * v8] + v10) = v9;
        }
        ++v10;
      }
      while ( v10 != 3 );
      ++v8;
    }
    while ( v8 != 3 );
    _sprintf_chk(&v16, 0, 100, "%d,0,0,0,%d,0,0,0,%d", v13[0], v14, v15);
    _android_log_print(4, "HW_DISPLAY_EFFECT", "%s: strTmp=%s", "hw_set_colortemperature", &v16);
    v11 = write(v5, &v16, 0x64u);
    close(v5);
    result = v11;
  }
  else
  {
    _android_log_print(
      6,
      "HW_DISPLAY_EFFECT",
      "%s: Err in open pri_lcd when set ColorTemperature",
      "hw_set_colortemperature");
    result = -1;
  }
  if ( v17 != _stack_chk_guard )
    _stack_chk_fail(result);
  return result;
}
// 970: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);
// 97C: using guessed type int _sprintf_chk(_DWORD, _DWORD, _DWORD, const char *, ...);
// 9A0: using guessed type int __fastcall _stack_chk_fail(_DWORD);
// B60: using guessed type int var_BC[4];

//----- (00000CC4) --------------------------------------------------------
signed int __fastcall hw_update_rgb_gamma(int a1, int _R1, int _R2)
{
  int v7; // r7@1
  signed int result; // r0@2
  int v9; // r4@3
  int v10; // r2@3
  int v11; // r5@4
  int v12; // ST14_4@12
  ssize_t v13; // r8@16
  int v14; // [sp+10h] [bp-C8h]@1
  int v15[4]; // [sp+1Ch] [bp-BCh]@12
  int v16; // [sp+2Ch] [bp-ACh]@16
  int v17; // [sp+3Ch] [bp-9Ch]@16
  char v18; // [sp+40h] [bp-98h]@16
  int v19; // [sp+A4h] [bp-34h]@1

  __asm { VMOV            S16, R1 }
  v14 = a1;
  __asm { VMOV            S17, R2 }
  v19 = _stack_chk_guard;
  v7 = open("/sys/class/graphics/fb0/lcd_color_temperature", 2);
  if ( v7 >= 0 )
  {
    v9 = 0;
    v10 = 0;
    do
    {
      v11 = 0;
      do
      {
        if ( v9 == v11 )
        {
          if ( v9 )
          {
            if ( v9 == 1 )
              __asm { VMOVEQ.F32      S0, S16 }
            else
              __asm { VMOVNE.F32      S0, S17 }
          }
          else
          {
            __asm { VLDR            S0, [SP,#0xD8+var_C8] }
          }
          v12 = v10;
          v15[4 * v9] = sub_B0A();
          v10 = v12;
        }
        else
        {
          *(&v15[3 * v9] + v11) = v10;
        }
        ++v11;
      }
      while ( v11 != 3 );
      ++v9;
    }
    while ( v9 != 3 );
    _sprintf_chk(&v18, 0, 100, "%d,0,0,0,%d,0,0,0,%d", v15[0], v16, v17);
    _android_log_print(4, "HW_DISPLAY_EFFECT", "%s: strTmp=%s", "hw_update_rgb_gamma", &v18);
    v13 = write(v7, &v18, 0x64u);
    close(v7);
    result = v13;
  }
  else
  {
    _android_log_print(6, "HW_DISPLAY_EFFECT", "%s: Err in open pri_lcd when update RgbGamma", "hw_update_rgb_gamma");
    result = -1;
  }
  if ( v19 != _stack_chk_guard )
    _stack_chk_fail(result);
  return result;
}
// 970: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);
// 97C: using guessed type int _sprintf_chk(_DWORD, _DWORD, _DWORD, const char *, ...);
// 9A0: using guessed type int __fastcall _stack_chk_fail(_DWORD);
// CC4: using guessed type int var_BC[4];

//----- (00000DD4) --------------------------------------------------------
int __fastcall hw_set_comfort_mode(unsigned int a1)
{
  unsigned int v1; // r6@3
  int v2; // r8@3
  ssize_t v3; // r4@4
  int v4; // r0@4
  int v5; // r7@5
  _DWORD *v6; // r0@8
  int result; // r0@11
  char v8; // [sp+8h] [bp-30h]@4
  int v9; // [sp+1Ch] [bp-1Ch]@3

  if ( a1 >= 0x32 )
    a1 = 50;
  v1 = a1;
  v9 = _stack_chk_guard;
  v2 = open("/sys/class/graphics/fb0/lcd_comform_mode", 2);
  if ( v2 < 0 )
  {
    v4 = dword_5004;
    if ( !dword_5004 )
    {
      v4 = _android_log_print(
             4,
             "HW_DISPLAY_EFFECT",
             "%s: write_value failed to open %s\n",
             "write_value",
             "/sys/class/graphics/fb0/lcd_comform_mode");
      dword_5004 = 1;
    }
  }
  else
  {
    _sprintf_chk(&v8, 0, 20, "%d\n", v1);
    v3 = write(v2, &v8, 0x14u);
    v4 = close(v2);
    if ( v3 != -1 )
    {
      v5 = 0;
      goto LABEL_10;
    }
  }
  v6 = (_DWORD *)_errno(v4);
  v5 = -*v6;
  if ( *v6 )
  {
    _android_log_print(6, "HW_DISPLAY_EFFECT", "%s: set_comfort_mode write_int err= %d \n", "hw_set_comfort_mode", -*v6);
    goto LABEL_11;
  }
LABEL_10:
  _android_log_print(
    4,
    "HW_DISPLAY_EFFECT",
    "%s: displayProcess.c set_comfort_mode set_comfortValue=%d\n",
    "hw_set_comfort_mode",
    v1);
LABEL_11:
  result = v5;
  if ( v9 != _stack_chk_guard )
    _stack_chk_fail(v5);
  return result;
}
// 970: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);
// 97C: using guessed type int _sprintf_chk(_DWORD, _DWORD, _DWORD, const char *, ...);
// 9A0: using guessed type int __fastcall _stack_chk_fail(_DWORD);
// 9AC: using guessed type int __cdecl _errno(_DWORD);
// 5004: using guessed type int dword_5004;

//----- (00000EC4) --------------------------------------------------------
int __fastcall hw_get_smart_display_supported(_DWORD *a1)
{
  _DWORD *v1; // r4@1
  int v2; // r0@1
  int result; // r0@2
  int v4; // r0@3

  v1 = a1;
  v2 = open("/sys/class/graphics/fb0/lcd_comform_mode", 2);
  if ( v2 < 0 )
  {
    v4 = _android_log_print(
           6,
           "HW_DISPLAY_EFFECT",
           "%s: Can't open COMFORM_MODE_FILE\n",
           "hw_get_smart_display_supported");
    result = -*(_DWORD *)_errno(v4);
  }
  else
  {
    *v1 = 1;
    close(v2);
    result = 0;
  }
  return result;
}
// 970: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);
// 9AC: using guessed type int __cdecl _errno(_DWORD);

//----- (00000F10) --------------------------------------------------------
int hw_update_color_temp_for_rg_led()
{
  return 0;
}

//----- (00000F14) --------------------------------------------------------
signed int __fastcall sub_F14(int a1, int a2, unsigned int a3, unsigned int a4)
{
  unsigned int v4; // r5@1
  unsigned int v5; // r7@1
  int v6; // r10@1
  int v7; // r4@1
  int v8; // r11@2
  unsigned int v9; // r8@7
  int v10; // r9@7
  int v11; // r0@8
  int v12; // r2@9
  int v13; // r1@10
  signed int result; // r0@10
  int v15; // r3@19
  int v16; // r2@19
  int v17; // r0@19
  int v18; // r1@19
  int v19; // r2@37
  int v20; // r0@39
  int v21; // r1@39
  int v22; // r3@39
  unsigned int v23; // r1@40
  unsigned int v24; // r0@40
  int v25; // r1@42
  int v26; // r6@45
  char v27; // r1@45
  int v29; // r0@50
  unsigned int v35; // r0@51
  int v36; // [sp+4h] [bp-34h]@58
  int v37; // [sp+8h] [bp-30h]@6
  int v38; // [sp+Ch] [bp-2Ch]@22
  int v39; // [sp+10h] [bp-28h]@8

  v4 = a4;
  v5 = a3;
  v6 = a2;
  v7 = a1;
  if ( a3 >= a4 )
    goto LABEL_58;
  v8 = 0;
  do
  {
    v9 = v5 + 1;
    v10 = *(_BYTE *)(v6 + (v5 ^ 3));
    if ( !(v10 & 0x80) )
    {
      sub_1790(v7, 13, &v39);
      v11 = 4 * v10;
      if ( v10 & 0x40 )
        v12 = -4 - (v11 & 0xFC) + v39;
      else
        v12 = v11 + v39 + 4;
      v39 = v12;
LABEL_23:
      sub_17C0(v7, 13, v12);
      ++v5;
      continue;
    }
    v13 = v10 & 0xF0;
    result = 9;
    if ( v13 > 159 )
    {
      if ( v13 > 191 )
      {
        if ( v13 == 192 )
        {
          switch ( v10 )
          {
            case 199:
              if ( !*(_BYTE *)(v6 + (v9 ^ 3)) || (unsigned int)*(_BYTE *)(v6 + (v9 ^ 3)) >= 0x10 )
                return 9;
              goto LABEL_55;
            case 192:
            case 193:
            case 194:
            case 195:
            case 196:
            case 197:
              v18 = 3;
              v16 = ((v10 & 7) + 1) | 0xA0000;
              v17 = v7;
              goto LABEL_33;
            case 200:
            case 201:
              v23 = *(_BYTE *)(v6 + (v9 ^ 3));
              v24 = v23 >> 4;
              if ( v10 == 200 )
                v24 = (v23 >> 4) | 0x10;
              v25 = v23 & 0xF;
              if ( (signed int)(v24 + v25) > 31 )
                return 9;
              v19 = (v25 + 1) | (v24 << 16);
              v20 = v7;
              v21 = 1;
              goto LABEL_53;
            case 198:
              v35 = *(_BYTE *)(v6 + (v9 ^ 3));
              if ( (signed int)((v35 & 0xF) + (v35 >> 4)) > 15 )
                return 9;
              v19 = ((v35 & 0xF) + 1) | (v35 >> 4 << 16);
              v20 = v7;
              v21 = 3;
LABEL_53:
              v22 = 5;
LABEL_54:
              sub_12FC(v20, v21, v19, v22);
              goto LABEL_55;
            default:
              return 9;
          }
          return 9;
        }
        if ( v13 != 208 )
          return result;
        if ( v10 & 8 )
          return 9;
        v18 = 1;
        v16 = ((v10 & 7) + 1) | 0x80000;
        v17 = v7;
LABEL_33:
        v15 = 5;
      }
      else
      {
        if ( v13 != 160 )
        {
          if ( v13 != 176 )
            return result;
          result = 9;
          switch ( v10 )
          {
            case 177:
              if ( v9 >= v4 )
                return 9;
              v19 = *(_BYTE *)(v6 + (v9 ^ 3));
              result = 9;
              if ( !*(_BYTE *)(v6 + (v9 ^ 3)) || v19 & 0xF0 )
                return result;
              v20 = v7;
              v21 = 0;
              v22 = 0;
              goto LABEL_54;
            case 178:
              if ( v9 >= v4 )
                return 9;
              v5 += 2;
              v26 = 0;
              v27 = 0;
              break;
            case 179:
              v22 = 1;
              v29 = *(_BYTE *)(v6 + (v9 ^ 3));
              _R1 = v29 << 12;
              __asm { UXTB16.W        R1, R1 }
              v19 = ((v29 & 0xF) + 1) | _R1;
              v20 = v7;
              v21 = 1;
              goto LABEL_54;
            case 176:
              goto LABEL_57;
            case 180:
            case 181:
            case 182:
            case 183:
              return result;
            default:
              v18 = 1;
              v15 = 1;
              v16 = ((v10 & 7) + 1) | 0x80000;
              v17 = v7;
              goto LABEL_34;
          }
          while ( 1 )
          {
            v26 |= (*(_BYTE *)(v6 + ((v5 - 1) ^ 3)) & 0x7F) << v27;
            if ( !(*(_BYTE *)(v6 + ((v5 - 1) ^ 3)) & 0x80) )
              break;
            _CF = v5 >= v4;
            v27 += 7;
            result = 9;
            ++v5;
            if ( _CF )
              return result;
          }
          sub_1790(v7, 13, &v37);
          v37 += 4 * v26 + 516;
          sub_17C0(v7, 13, v37);
          continue;
        }
        v15 = 0;
        v16 = ((16 << ((*(_BYTE *)(v6 + (v5 ^ 3)) & 7) + 1)) - 16) | (*(_BYTE *)(v6 + (v5 ^ 3)) << 11) & 0x4000;
        v17 = v7;
        v18 = 0;
      }
LABEL_34:
      sub_12FC(v17, v18, v16, v15);
      ++v5;
      continue;
    }
    if ( v13 != 128 )
    {
      if ( v13 != 144 )
        return result;
      if ( (v10 & 0xF | 2) == 15 )
        return 9;
      sub_1790(v7, v10 & 0xF, &v38);
      v12 = v38;
      goto LABEL_23;
    }
    if ( v9 >= v4 || !((unsigned __int16)((_WORD)v10 << 12) | 16 * *(_BYTE *)(v6 + ((v5 + 1) ^ 3))) )
      return 9;
    sub_12FC(v7, 0, (unsigned __int16)((_WORD)v10 << 12) | 16 * *(_BYTE *)(v6 + (v9 ^ 3)), 0);
    v8 |= (((_WORD)v10 << 12) & 0x8000u) >> 15;
LABEL_55:
    v5 += 2;
  }
  while ( v5 < v4 );
LABEL_57:
  if ( v8 & 1 )
    return 8;
LABEL_58:
  sub_1790(v7, 14, &v36);
  sub_17C0(v7, 15, v36);
  return 8;
}

//----- (00001258) --------------------------------------------------------
signed int __fastcall sub_1258(int a1, int a2, unsigned int a3, int a4, int *a5)
{
  int v5; // r5@1
  int v6; // r4@1
  signed int result; // r0@2
  int v8; // r2@4
  int v9; // r0@4
  int v10; // r1@4
  __int64 v11; // r2@10
  int v12; // r1@10

  v5 = a3;
  v6 = a1;
  switch ( a2 )
  {
    case 0:
      result = 2;
      if ( a3 > 0xF || a4 )
        return result;
      v8 = *a5;
      v9 = v6;
      v10 = v5;
      goto LABEL_14;
    case 1:
      if ( a4 == 5 )
      {
        if ( a3 <= 0x1F )
          goto LABEL_21;
        return 2;
      }
      if ( a4 != 1 || a3 > 0xF )
        return 2;
      sub_18AC(a1);
LABEL_21:
      v11 = *(_QWORD *)a5;
      v12 = v5 + 256;
LABEL_22:
      result = sub_1834(v6, v12, v11, SHIDWORD(v11));
LABEL_23:
      if ( result )
        result = 2;
      return result;
    case 3:
      result = 2;
      if ( a3 > 0x1F || a4 != 5 )
        return result;
      v11 = *(_QWORD *)a5;
      v12 = v5 + 112;
      goto LABEL_22;
    case 4:
      result = 2;
      if ( a3 > 3 || a4 )
        return result;
      v8 = *a5;
      v10 = v5 + 192;
      v9 = v6;
LABEL_14:
      result = sub_17C0(v9, v10, v8);
      goto LABEL_23;
    default:
      sub_1634(
        (int)"_Unwind_VRS_Result _Unwind_VRS_Set(_Unwind_Context *, _Unwind_VRS_RegClass, uint32_t, _Unwind_VRS_DataRepre"
             "sentation, void *)",
        831,
        (int)"unsupported register class");
      return result;
  }
}

//----- (000012FC) --------------------------------------------------------
signed int __fastcall sub_12FC(int a1, int a2, unsigned int a3, int a4)
{
  int v4; // r5@1
  int v5; // r7@1
  unsigned int v6; // r6@1
  int v7; // r8@1
  int v8; // r4@4
  unsigned int v9; // r7@4
  int *v10; // r0@6
  signed int v11; // r0@6
  signed int v12; // r1@6
  signed int v13; // r2@6
  signed int result; // r0@14
  unsigned int v15; // r4@18
  unsigned int v16; // r6@18
  int v17; // r0@19
  int v18; // r2@19
  int v19; // r0@19
  int v20; // r2@22
  int v21; // [sp+8h] [bp-38h]@19
  int v22; // [sp+Ch] [bp-34h]@19
  int v23; // [sp+14h] [bp-2Ch]@16
  int v24; // [sp+18h] [bp-28h]@6
  int *v25; // [sp+1Ch] [bp-24h]@3

  v4 = a2;
  v5 = a4;
  v6 = a3;
  v7 = a1;
  switch ( a2 )
  {
    case 0:
    case 4:
      if ( a4 || sub_1790(a1, 13, &v25) )
        return 2;
      v8 = 0;
      v9 = 0;
      do
      {
        if ( (1 << v9) & v6 )
        {
          v10 = v25;
          ++v25;
          v24 = *v10;
          v11 = sub_1258(v7, v4, v9, 0, &v24);
          v12 = 0;
          v13 = 0;
          if ( v9 == 13 )
            v12 = 1;
          if ( !v4 )
            v13 = 1;
          if ( v11 )
            return 2;
          v8 |= v13 & v12;
        }
        ++v9;
      }
      while ( v9 < 0x10 );
      if ( v8 & 1 )
        return 0;
      v20 = (int)v25;
      goto LABEL_28;
    case 1:
    case 3:
      if ( (a4 | 4) != 5 || sub_1790(a1, 13, &v23) )
        return 2;
      if ( !(_WORD)v6 )
        goto LABEL_21;
      v15 = v6 >> 16;
      v16 = (v6 >> 16) + v6;
      break;
    default:
      sub_1634(
        (int)"_Unwind_VRS_Result _Unwind_VRS_Pop(_Unwind_Context *, _Unwind_VRS_RegClass, uint32_t, _Unwind_VRS_DataRepresentation)",
        965,
        (int)"unsupported register class");
      return result;
  }
  do
  {
    v17 = v23;
    v23 += 4;
    v18 = *(_DWORD *)v17;
    v23 = v17 + 8;
    v19 = *(_DWORD *)(v17 + 4);
    v21 = v18;
    v22 = v19;
    if ( sub_1258(v7, v4, v15, v5, &v21) )
      return 2;
    ++v15;
  }
  while ( v15 < v16 );
LABEL_21:
  if ( v5 == 1 )
  {
    v20 = v23 + 4;
    v23 += 4;
  }
  else
  {
    v20 = v23;
  }
LABEL_28:
  result = sub_17C0(v7, 13, v20);
  if ( result )
    result = 2;
  return result;
}

//----- (00001420) --------------------------------------------------------
signed int __fastcall sub_1420(int a1, int a2, int a3)
{
  int v3; // r0@1
  int v4; // r1@1
  unsigned int *v5; // r12@1
  int v6; // r3@1
  unsigned int v7; // r3@4
  unsigned int v8; // r2@4

  v3 = a2;
  v4 = a3;
  v5 = *(unsigned int **)(v3 + 76);
  v6 = (*v5 >> 24) & 0xF;
  if ( v6 )
  {
    if ( v6 != 1 && v6 != 3 )
      return 9;
    v7 = 4 * ((*v5 >> 16) & 0xFF) + 4;
    v8 = 2;
  }
  else
  {
    v8 = 1;
    v7 = 4;
  }
  if ( !v5 || !(*(_BYTE *)(v3 + 80) & 1) && *(unsigned int *)((char *)v5 + v7) )
    return 9;
  return sub_F14(v4, (int)v5, v8, v7);
}

//----- (00001474) --------------------------------------------------------
void sub_1474()
{
  JUMPOUT(&loc_1428);
}

//----- (0000147C) --------------------------------------------------------
void sub_147C()
{
  JUMPOUT(&loc_1428);
}

//----- (00001518) --------------------------------------------------------
signed int __fastcall sub_1518(int a1, int a2, char a3)
{
  int v3; // r4@1
  char v4; // r10@1
  signed int i; // r6@1
  signed int v6; // r7@3
  int v7; // r0@8
  int (__fastcall *v8)(signed int, int, char *); // r3@11
  int v9; // r0@12
  int v11; // [sp+0h] [bp-4B0h]@17
  int v12; // [sp+4h] [bp-4ACh]@10
  int (__fastcall *v13)(signed int, int, char *); // [sp+10h] [bp-4A0h]@11
  int v14; // [sp+18h] [bp-498h]@12
  int v15; // [sp+24h] [bp-48Ch]@12
  int v16; // [sp+2Ch] [bp-484h]@10
  char v17; // [sp+30h] [bp-480h]@1

  v3 = a2;
  v4 = a3;
  sub_1740((int)&v17);
  for ( i = 1; ; --i )
  {
    v6 = 1;
    if ( v4 & 1 )
    {
      v6 = 2;
      if ( !i )
      {
        sub_17C0((int)&v17, -1, *(_DWORD *)(v3 + 16));
        v4 = 0;
      }
    }
    v7 = sub_186C((int)&v17);
    if ( !v7 )
      break;
    if ( v7 < 0 )
      return 2;
    sub_1790((int)&v17, -2, &v16);
    if ( sub_1874((int)&v17, (int)&v12) )
      return 2;
    v8 = v13;
    if ( v13 )
    {
      *(_DWORD *)(v3 + 72) = v12;
      *(_DWORD *)(v3 + 76) = v15;
      *(_DWORD *)(v3 + 80) = v14;
      v9 = v8(v6, v3, &v17);
      if ( v9 == 7 )
      {
        sub_1790((int)&v17, -1, &v11);
        *(_DWORD *)(v3 + 16) = v11;
        sub_1894((int)&v17);
        return 2;
      }
      if ( v9 == 9 )
        abort();
      if ( v9 != 8 )
        return 2;
      if ( v16 == *(_DWORD *)(v3 + 32) )
        sub_1634(
          (int)"_Unwind_Reason_Code unwind_phase2(unw_context_t *, _Unwind_Exception *, bool)",
          642,
          (int)"during phase1 personality function said it would stop here, but now in phase2 it did not stop here");
    }
  }
  return 5;
}

//----- (00001634) --------------------------------------------------------
void __fastcall sub_1634(int a1, int a2, int a3)
{
  fprintf((FILE *)stderr, "libunwind: %s %s:%d - %s\n", a1, "external/libcxxabi/src/Unwind/Unwind-EHABI.cpp", a2, a3);
  abort();
}

//----- (000016B8) --------------------------------------------------------
int __fastcall sub_16B8(int a1, int a2, int a3, int a4, int a5)
{
  int v5; // r4@0
  int v6; // r5@0
  int v7; // r6@0
  int v8; // r7@0
  int v9; // r8@0
  int v10; // r9@0
  int v11; // r10@0
  int v12; // r11@0
  int v13; // r12@0
  int v14; // lr@0

  *(_DWORD *)a1 = a1;
  *(_DWORD *)(a1 + 4) = a2;
  *(_DWORD *)(a1 + 8) = a3;
  *(_DWORD *)(a1 + 12) = a4;
  *(_DWORD *)(a1 + 16) = v5;
  *(_DWORD *)(a1 + 20) = v6;
  *(_DWORD *)(a1 + 24) = v7;
  *(_DWORD *)(a1 + 28) = v8;
  *(_DWORD *)(a1 + 32) = v9;
  *(_DWORD *)(a1 + 36) = v10;
  *(_DWORD *)(a1 + 40) = v11;
  *(_DWORD *)(a1 + 44) = v12;
  *(_DWORD *)(a1 + 48) = v13;
  *(_DWORD *)(a1 + 52) = &a5;
  *(_DWORD *)(a1 + 56) = v14;
  *(_DWORD *)(a1 + 60) = v14;
  return 0;
}

//----- (000016D0) --------------------------------------------------------
int __fastcall sub_16D0(int _R0)
{
  int result; // r0@1

  __asm { VSTMIA          R0, {D0-D15} }
  return result;
}

//----- (000016D8) --------------------------------------------------------
int __fastcall sub_16D8(int _R0)
{
  int result; // r0@1

  __asm { VSTMIA          R0, {D0-D15} }
  return result;
}

//----- (000016E0) --------------------------------------------------------
int __fastcall sub_16E0(int _R0)
{
  int result; // r0@1

  __asm { VSTMIA          R0, {D16-D31} }
  return result;
}

//----- (000016E8) --------------------------------------------------------
void sub_16E8()
{
  __asm
  {
    STCL            p1, c0, [R0],#8
    STCL            p1, c1, [R0],#8
    STCL            p1, c2, [R0],#8
    STCL            p1, c3, [R0],#8
    STCL            p1, c4, [R0],#8
    STCL            p1, c5, [R0],#8
    STCL            p1, c6, [R0],#8
    STCL            p1, c7, [R0],#8
    STCL            p1, c8, [R0],#8
    STCL            p1, c9, [R0],#8
    STCL            p1, c10, [R0],#8
    STCL            p1, c11, [R0],#8
    STCL            p1, c12, [R0],#8
    STCL            p1, c13, [R0],#8
    STCL            p1, c14, [R0],#8
    STCL            p1, c15, [R0],#8
  }
}

//----- (0000172C) --------------------------------------------------------
void sub_172C()
{
  __asm
  {
    STC2            p1, c8, [R0],#4
    STC2            p1, c9, [R0],#4
    STC2            p1, c10, [R0],#4
    STC2            p1, c11, [R0],#4
  }
}

//----- (00001740) --------------------------------------------------------
int __fastcall sub_1740(int a1)
{
  int v1; // r4@1

  v1 = a1;
  *(_DWORD *)a1 = &off_4E20;
  *(_DWORD *)(a1 + 4) = &unk_5008;
  *(_BYTE *)(a1 + 76) = 0;
  *(_DWORD *)(a1 + 72) = 0;
  _aeabi_memcpy(a1 + 8);
  _aeabi_memset(v1 + 80, 450, 0);
  sub_1CC4(v1, 0);
  return 0;
}
// 9D0: using guessed type int __fastcall _aeabi_memcpy(_DWORD);
// 9DC: using guessed type int __fastcall _aeabi_memset(_DWORD, _DWORD, _DWORD);
// 4E20: using guessed type void *;

//----- (00001790) --------------------------------------------------------
signed int __fastcall sub_1790(int a1, int a2, _DWORD *a3)
{
  int v3; // r6@1
  _DWORD *v4; // r4@1
  int v5; // r5@1
  signed int result; // r0@2

  v3 = a1;
  v4 = a3;
  v5 = a2;
  if ( (*(int (**)(void))(*(_DWORD *)a1 + 8))() == 1 )
  {
    *v4 = (*(int (__fastcall **)(int, int))(*(_DWORD *)v3 + 12))(v3, v5);
    result = 0;
  }
  else
  {
    result = -6542;
  }
  return result;
}

//----- (000017C0) --------------------------------------------------------
signed int __fastcall sub_17C0(int a1, int a2, int a3)
{
  int v3; // r4@1
  int v4; // r6@1
  int v5; // r5@1
  signed int v6; // r5@3

  v3 = a1;
  v4 = a3;
  v5 = a2;
  if ( (*(int (**)(void))(*(_DWORD *)a1 + 8))() == 1 )
  {
    (*(void (__fastcall **)(int, int, int))(*(_DWORD *)v3 + 16))(v3, v5, v4);
    if ( v5 == -1 )
    {
      v6 = 0;
      (*(void (__fastcall **)(int, _DWORD))(*(_DWORD *)v3 + 52))(v3, 0);
    }
    else
    {
      v6 = 0;
    }
  }
  else
  {
    v6 = -6542;
  }
  return v6;
}

//----- (00001804) --------------------------------------------------------
signed int __fastcall sub_1804(int a1, int a2, _QWORD *a3)
{
  int v3; // r6@1
  _QWORD *v4; // r4@1
  int v5; // r5@1
  __int64 v6; // r0@2
  signed int result; // r0@2

  v3 = a1;
  v4 = a3;
  v5 = a2;
  if ( (*(int (**)(void))(*(_DWORD *)a1 + 20))() == 1 )
  {
    LODWORD(v6) = (*(int (__fastcall **)(int, int))(*(_DWORD *)v3 + 24))(v3, v5);
    *v4 = v6;
    result = 0;
  }
  else
  {
    result = -6542;
  }
  return result;
}

//----- (00001834) --------------------------------------------------------
signed int __fastcall sub_1834(int a1, int a2, int a3, int a4)
{
  int v4; // r7@1
  int v5; // r5@1
  int v6; // r6@1
  int v7; // r8@1
  signed int result; // r0@2

  v4 = a1;
  v5 = a3;
  v6 = a2;
  v7 = a4;
  if ( (*(int (**)(void))(*(_DWORD *)a1 + 20))() == 1 )
  {
    (*(void (__fastcall **)(int, int, int, int))(*(_DWORD *)v4 + 28))(v4, v6, v5, v7);
    result = 0;
  }
  else
  {
    result = -6542;
  }
  return result;
}

//----- (0000186C) --------------------------------------------------------
int __fastcall sub_186C(int a1)
{
  return (*(int (**)(void))(*(_DWORD *)a1 + 32))();
}

//----- (00001874) --------------------------------------------------------
signed int __fastcall sub_1874(int a1, int a2)
{
  int v2; // r4@1
  signed int result; // r0@1

  v2 = a2;
  (*(void (**)(void))(*(_DWORD *)a1 + 36))();
  result = 0;
  if ( !*(_DWORD *)(v2 + 4) )
    result = -6549;
  return result;
}

//----- (00001894) --------------------------------------------------------
signed int __fastcall sub_1894(int a1)
{
  (*(void (**)(void))(*(_DWORD *)a1 + 40))();
  return -6540;
}

//----- (000018AC) --------------------------------------------------------
int __fastcall sub_18AC(int a1)
{
  return (*(int (**)(void))(*(_DWORD *)a1 + 60))();
}

//----- (000018BC) --------------------------------------------------------
int __fastcall sub_18BC(int a1, int a2)
{
  signed int v2; // r2@1
  bool v3; // zf@1
  signed int v4; // r0@1
  unsigned int v5; // r1@1

  v2 = 0;
  v3 = (a2 & 0xFFFFFFFC) == 192;
  v4 = 0;
  v5 = a2 - 16;
  if ( v3 )
    v4 = 1;
  if ( v5 > 0xFFFFFFED )
    v2 = 1;
  return v4 | v2;
}

//----- (000018E0) --------------------------------------------------------
int __fastcall sub_18E0(int a1, signed int a2)
{
  signed int v2; // r5@1
  int v3; // r4@1
  int v4; // r0@7

  v2 = a2;
  v3 = a1;
  if ( a2 >= -1 )
  {
    if ( a2 > 13 )
    {
      if ( a2 == 14 )
      {
        v4 = a1 + 64;
        return *(_DWORD *)v4;
      }
      if ( a2 != 15 )
        goto LABEL_12;
    }
    else if ( a2 != -1 )
    {
      if ( a2 != 13 )
        goto LABEL_12;
LABEL_7:
      v4 = a1 + 60;
      return *(_DWORD *)v4;
    }
    v4 = a1 + 68;
    return *(_DWORD *)v4;
  }
  if ( a2 == -2 )
    goto LABEL_7;
LABEL_12:
  if ( (unsigned int)a2 > 0xC )
  {
    if ( (a2 & 0xFFFFFFFC) != 192 )
      sub_1D20(
        (int)"uint32_t libunwind::Registers_arm::getRegister(int)",
        (int)"external/libcxxabi/src/Unwind/Registers.hpp",
        1452,
        (int)"unsupported arm register");
    if ( !*(_BYTE *)(a1 + 76) )
    {
      *(_BYTE *)(a1 + 76) = 1;
      sub_172C();
    }
    v4 = v3 + 4 * v2 - 296;
  }
  else
  {
    v4 = a1 + 4 * a2 + 8;
  }
  return *(_DWORD *)v4;
}

//----- (0000197C) --------------------------------------------------------
int __fastcall sub_197C(int result, signed int a2, int a3)
{
  signed int v3; // r6@1
  int v4; // r4@1
  int v5; // r5@1

  v3 = a2;
  v4 = a3;
  v5 = result;
  if ( a2 >= -1 )
  {
    if ( a2 > 13 )
    {
      if ( a2 == 14 )
      {
        *(_DWORD *)(result + 64) = a3;
        return result;
      }
      if ( a2 != 15 )
        goto LABEL_12;
    }
    else if ( a2 != -1 )
    {
      if ( a2 != 13 )
        goto LABEL_12;
LABEL_7:
      *(_DWORD *)(result + 60) = a3;
      return result;
    }
    *(_DWORD *)(result + 68) = a3;
    return result;
  }
  if ( a2 == -2 )
    goto LABEL_7;
LABEL_12:
  if ( (unsigned int)a2 > 0xC )
  {
    if ( (a2 & 0xFFFFFFFC) != 192 )
      sub_1D20(
        (int)"void libunwind::Registers_arm::setRegister(int, uint32_t)",
        (int)"external/libcxxabi/src/Unwind/Registers.hpp",
        1471,
        (int)"unsupported arm register");
    if ( !*(_BYTE *)(result + 76) )
    {
      *(_BYTE *)(result + 76) = 1;
      sub_172C();
    }
    result = v5 + 4 * v3;
    *(_DWORD *)(result - 296) = v4;
  }
  else
  {
    result += 4 * a2;
    *(_DWORD *)(result + 8) = a3;
  }
  return result;
}

//----- (00001A14) --------------------------------------------------------
int __fastcall sub_1A14(int a1, int a2)
{
  signed int v2; // r2@1
  bool v3; // zf@1
  signed int v4; // r0@1
  unsigned int v5; // r1@1

  v2 = 0;
  v3 = (a2 & 0xFFFFFFF0) == 112;
  v4 = 0;
  v5 = a2 & 0xFFFFFFE0;
  if ( v3 )
    v4 = 1;
  if ( v5 == 256 )
    v2 = 1;
  return v4 | v2;
}

//----- (00001A38) --------------------------------------------------------
__int64 __fastcall sub_1A38(int a1, int a2)
{
  int v2; // r4@1
  int v3; // r5@1
  unsigned int v4; // r0@1
  int v5; // r0@5
  int v6; // r0@11

  v2 = a2;
  v3 = a1;
  v4 = a2 & 0xFFFFFFF0;
  if ( (a2 & 0xFFFFFFF0) == 112 )
  {
    if ( !*(_BYTE *)(v3 + 75) )
    {
      *(_BYTE *)(v3 + 75) = 1;
      sub_16E8();
    }
    v5 = v3 + 8 * v2 - 552;
  }
  else if ( v4 == 272 )
  {
    if ( !*(_BYTE *)(v3 + 74) )
    {
      *(_BYTE *)(v3 + 74) = 1;
      sub_16E0(v3 + 216);
    }
    v5 = v3 + 8 * v2 - 1960;
  }
  else
  {
    if ( v4 != 256 )
      sub_1D20(
        (int)"unw_fpreg_t libunwind::Registers_arm::getFloatRegister(int)",
        (int)"external/libcxxabi/src/Unwind/Registers.hpp",
        1673,
        (int)"Unknown ARM float register");
    if ( !*(_BYTE *)(v3 + 73) )
    {
      *(_BYTE *)(v3 + 73) = 1;
      v6 = v3 + 80;
      if ( *(_BYTE *)(v3 + 72) )
        sub_16D8(v6);
      else
        sub_16D0(v6);
    }
    v5 = v3 + 8 * v2 - 1968;
  }
  return *(_QWORD *)v5;
}

//----- (00001AE8) --------------------------------------------------------
int __fastcall sub_1AE8(int a1, int a2, int a3, int a4)
{
  int v4; // r6@1
  int v5; // r7@1
  unsigned int v6; // r0@1
  int v7; // r5@1
  int v8; // r4@1
  int result; // r0@5
  int v10; // r1@5
  int v11; // r0@11

  v4 = a2;
  v5 = a1;
  v6 = a2 & 0xFFFFFFF0;
  v7 = a4;
  v8 = a3;
  if ( (a2 & 0xFFFFFFF0) == 112 )
  {
    if ( !*(_BYTE *)(v5 + 75) )
    {
      *(_BYTE *)(v5 + 75) = 1;
      sub_16E8();
    }
    result = v5 + 8 * v4;
    *(_DWORD *)(result - 548) = v7;
    LOWORD(v10) = -552;
  }
  else if ( v6 == 272 )
  {
    if ( !*(_BYTE *)(v5 + 74) )
    {
      *(_BYTE *)(v5 + 74) = 1;
      sub_16E0(v5 + 216);
    }
    result = v5 + 8 * v4;
    *(_DWORD *)(result - 1828) = v7;
    LOWORD(v10) = -1832;
  }
  else
  {
    if ( v6 != 256 )
      sub_1D20(
        (int)"void libunwind::Registers_arm::setFloatRegister(int, unw_fpreg_t)",
        (int)"external/libcxxabi/src/Unwind/Registers.hpp",
        1700,
        (int)"Unknown ARM float register");
    if ( !*(_BYTE *)(v5 + 73) )
    {
      *(_BYTE *)(v5 + 73) = 1;
      v11 = v5 + 80;
      if ( *(_BYTE *)(v5 + 72) )
        sub_16D8(v11);
      else
        sub_16D0(v11);
    }
    result = v5 + 8 * v4;
    *(_DWORD *)(result - 1964) = v7;
    LOWORD(v10) = -1968;
  }
  HIWORD(v10) = -1;
  *(_DWORD *)(result + v10) = v8;
  return result;
}

//----- (00001BBC) --------------------------------------------------------
signed int __fastcall sub_1BBC(int a1)
{
  int v1; // r4@1
  signed int result; // r0@3
  void (__fastcall *v3)(int, signed int, int); // r5@5
  int v4; // r0@5

  v1 = a1;
  if ( *(_BYTE *)(a1 + 528)
    || ((*(void (__fastcall **)(int, signed int))(*(_DWORD *)a1 + 52))(a1, 1), *(_BYTE *)(v1 + 528)) )
  {
    result = 0;
  }
  else
  {
    if ( *(_DWORD *)(v1 + 504) )
    {
      v3 = *(void (__fastcall **)(int, signed int, int))(*(_DWORD *)v1 + 16);
      v4 = (*(int (__fastcall **)(int, signed int))(*(_DWORD *)v1 + 12))(v1, -2);
      v3(v1, -2, *(_DWORD *)(v1 + 504) + v4);
    }
    result = 1;
  }
  return result;
}

//----- (00001C08) --------------------------------------------------------
int __fastcall sub_1C08(int a1, int a2)
{
  int v2; // r3@1
  int v3; // r4@1
  int v4; // r5@1
  int v5; // r12@1
  int v6; // lr@1
  int v7; // r4@1
  int v8; // r2@1
  int v9; // r3@1
  int v10; // r5@1
  int result; // r0@1

  v2 = *(_DWORD *)(a1 + 504);
  v3 = *(_DWORD *)(a1 + 496);
  v4 = *(_DWORD *)(a1 + 500);
  v5 = *(_DWORD *)(a1 + 488);
  v6 = *(_DWORD *)(a1 + 492);
  *(_DWORD *)(a2 + 20) = *(_DWORD *)(a1 + 508);
  *(_DWORD *)(a2 + 16) = v2;
  *(_DWORD *)(a2 + 12) = v4;
  *(_DWORD *)(a2 + 8) = v3;
  v7 = a2 + 24;
  *(_DWORD *)a2 = v5;
  *(_DWORD *)(a2 + 4) = v6;
  v8 = *(_DWORD *)(a1 + 512);
  v9 = *(_DWORD *)(a1 + 516);
  v10 = *(_DWORD *)(a1 + 520);
  result = *(_DWORD *)(a1 + 524);
  *(_DWORD *)(a2 + 36) = result;
  *(_DWORD *)v7 = v8;
  *(_DWORD *)(v7 + 4) = v9;
  *(_DWORD *)(v7 + 8) = v10;
  return result;
}

//----- (00001C48) --------------------------------------------------------
void __fastcall sub_1C48(int a1)
{
  sub_1D54(a1 + 8);
  sub_26F0();
}

//----- (00001C60) --------------------------------------------------------
int __fastcall sub_1C60(int a1)
{
  return *(_BYTE *)(a1 + 529);
}

//----- (00001C68) --------------------------------------------------------
signed int __fastcall sub_1C68(int a1, int a2, int a3, _DWORD *a4)
{
  int v4; // r6@1
  int v5; // r5@1
  _DWORD *v6; // r4@1
  int v7; // r7@1
  signed int result; // r0@3
  int v9; // [sp+10h] [bp-20h]@2
  int v10; // [sp+14h] [bp-1Ch]@3

  v4 = a2;
  v5 = a3;
  v6 = a4;
  v7 = (*(int (**)(void))(*(_DWORD *)a1 + 12))();
  if ( dladdr() && v9 )
  {
    _snprintf_chk(v4, v5, 0, -1);
    *v6 = v7 - v10;
    result = 1;
  }
  else
  {
    result = 0;
  }
  return result;
}
// 9E8: using guessed type int dladdr(void);
// 9F4: using guessed type int __fastcall _snprintf_chk(_DWORD, _DWORD, _DWORD, _DWORD);

//----- (00001CC4) --------------------------------------------------------
int __fastcall sub_1CC4(int a1, int a2)
{
  int v2; // r4@1
  int v3; // r6@1
  unsigned int v4; // r5@1
  int result; // r0@5
  int v6; // [sp+4h] [bp-1Ch]@3
  int v7; // [sp+8h] [bp-18h]@3
  int v8; // [sp+Ch] [bp-14h]@1

  v2 = a1;
  v3 = a2;
  v4 = (*(int (**)(void))(*(_DWORD *)a1 + 12))() & 0xFFFFFFFE;
  v8 = 0;
  if ( v3 )
    --v4;
  v6 = _gnu_Unwind_Find_exidx(v4, &v8);
  v7 = v8;
  if ( !v6 || !v8 || (result = ((int (__fastcall *)(int, unsigned int, int *))sub_1DA4)(v2, v4, &v6)) == 0 )
  {
    result = 1;
    *(_BYTE *)(v2 + 528) = 1;
  }
  return result;
}
// A00: using guessed type int __fastcall _gnu_Unwind_Find_exidx(_DWORD, _DWORD);
// 1DA4: using guessed type int sub_1DA4();

//----- (00001D10) --------------------------------------------------------
const char *__fastcall sub_1D10(int a1, signed int a2)
{
  const char *result; // r0@2
  signed int v3; // r0@3
  int *v4; // r1@3

  if ( a2 > 255 )
  {
    switch ( a2 )
    {
      case 256:
        v3 = -7934;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 257:
        v3 = -7931;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 258:
        v3 = -7928;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 259:
        v3 = -7925;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 260:
        v3 = -7922;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 261:
        v3 = -7919;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 262:
        v3 = -7916;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 263:
        v3 = -7913;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 264:
        v3 = -7910;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 265:
        v3 = -7907;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 266:
        v3 = -7904;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 267:
        v3 = -7900;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 268:
        v3 = -7896;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 269:
        v3 = -7892;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 270:
        v3 = -7888;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 271:
        v3 = -7884;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 272:
        v3 = -7880;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 273:
        v3 = -7876;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 274:
        v3 = -7872;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 275:
        v3 = -7868;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 276:
        v3 = -7864;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 277:
        v3 = -7860;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 278:
        v3 = -7856;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 279:
        v3 = -7852;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 280:
        v3 = -7848;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 281:
        v3 = -7844;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 282:
        v3 = -7840;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 283:
        v3 = -7836;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 284:
        v3 = -7832;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 285:
        v3 = -7828;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 286:
        v3 = -7824;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 287:
        v3 = -7820;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      default:
def_2080:
        v3 = -7816;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
    }
  }
  else
  {
    result = "pc";
    switch ( a2 + 2 )
    {
      case 0:
      case 15:
        v3 = -8097;
        v4 = &GLOBAL_OFFSET_TABLE_;
        return (char *)v4 + v3;
      default:
        goto def_2080;
      case 1:
      case 17:
        return result;
      case 2:
        v3 = -8094;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 3:
        v3 = -8091;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 4:
        v3 = -8088;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 5:
        v3 = -8085;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 6:
        v3 = -8082;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 7:
        v3 = -8079;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 8:
        v3 = -8076;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 9:
        v3 = -8073;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 10:
        v3 = -8070;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 11:
        v3 = -8067;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 12:
        v3 = -8064;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 13:
        v3 = -8060;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 14:
        v3 = -8056;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 16:
        v3 = -8100;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 66:
        v3 = -8052;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 67:
        v3 = -8049;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 68:
        v3 = -8046;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 69:
        v3 = -8043;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 70:
        v3 = -8040;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 71:
        v3 = -8037;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 72:
        v3 = -8034;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 73:
        v3 = -8031;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 74:
        v3 = -8028;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 75:
        v3 = -8025;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 76:
        v3 = -8022;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 77:
        v3 = -8018;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 78:
        v3 = -8014;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 79:
        v3 = -8010;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 80:
        v3 = -8006;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 81:
        v3 = -8002;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 82:
        v3 = -7998;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 83:
        v3 = -7994;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 84:
        v3 = -7990;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 85:
        v3 = -7986;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 86:
        v3 = -7982;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 87:
        v3 = -7978;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 88:
        v3 = -7974;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 89:
        v3 = -7970;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 90:
        v3 = -7966;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 91:
        v3 = -7962;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 92:
        v3 = -7958;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 93:
        v3 = -7954;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 94:
        v3 = -7950;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 95:
        v3 = -7946;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 96:
        v3 = -7942;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 97:
        v3 = -7938;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
    }
  }
  return (char *)v4 + v3;
}
// 4F98: using guessed type int GLOBAL_OFFSET_TABLE_;

//----- (00001D18) --------------------------------------------------------
int __fastcall sub_1D18(int result)
{
  *(_BYTE *)(result + 72) = 1;
  return result;
}

//----- (00001D20) --------------------------------------------------------
void __fastcall sub_1D20(int a1, int a2, int a3, int a4)
{
  fprintf((FILE *)stderr, "libunwind: %s %s:%d - %s\n", a1, a2, a3, a4);
  abort();
}

//----- (00001D54) --------------------------------------------------------
int __fastcall sub_1D54(int a1)
{
  int v1; // r4@1
  int v2; // r0@2
  int result; // r0@9

  v1 = a1;
  if ( *(_BYTE *)(a1 + 65) )
  {
    v2 = a1 + 72;
    if ( *(_BYTE *)(v1 + 64) )
      sub_2628(v2);
    else
      sub_2620(v2);
  }
  if ( *(_BYTE *)(v1 + 66) )
    sub_2630(v1 + 208);
  if ( *(_BYTE *)(v1 + 67) )
    sub_2638((_DWORD *)(v1 + 336));
  result = *(_BYTE *)(v1 + 68);
  if ( *(_BYTE *)(v1 + 68) )
    result = sub_2700((_DWORD *)(v1 + 464));
  return result;
}

//----- (00001F34) --------------------------------------------------------
int __fastcall sub_1F34(int result, int a2, int a3, _DWORD *a4, int a5, int a6, int a7, _DWORD *a8)
{
  unsigned int v8; // r4@1
  unsigned int v9; // r5@2
  int v10; // r6@3

  v8 = a5 - a2;
  while ( 1 )
  {
    v9 = v8;
    if ( !v8 )
      break;
    v10 = a2 + (v8 >> 1);
    v8 >>= 1;
    if ( *a8 >= *a4 + 8 * v10 + (2 * *(_DWORD *)(*a4 + 8 * v10) & 0x80000000 | *(_DWORD *)(*a4 + 8 * v10)) )
    {
      v8 = v9 - 1 - v8;
      a2 = v10 + 1;
    }
  }
  *(_DWORD *)result = a2;
  *(_DWORD *)(result + 4) = a3;
  *(_DWORD *)(result + 8) = a4;
  return result;
}

//----- (00002620) --------------------------------------------------------
int __fastcall sub_2620(int _R0)
{
  int result; // r0@1

  __asm { VLDMIA          R0, {D0-D15} }
  return result;
}

//----- (00002628) --------------------------------------------------------
int __fastcall sub_2628(int _R0)
{
  int result; // r0@1

  __asm { VLDMIA          R0, {D0-D15} }
  return result;
}

//----- (00002630) --------------------------------------------------------
int __fastcall sub_2630(int _R0)
{
  int result; // r0@1

  __asm { VLDMIA          R0, {D16-D31} }
  return result;
}

//----- (00002638) --------------------------------------------------------
int __fastcall sub_2638(_DWORD *a1)
{
  int *v5; // r0@1
  int result; // r0@1

  _T1 = *a1;
  v5 = a1 + 2;
  __asm { LDCL            p1, c0, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c1, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c2, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c3, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c4, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c5, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c6, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c7, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c8, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c9, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c10, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c11, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c12, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c13, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c14, [R0],#8 }
  _T1 = *v5;
  result = (int)(v5 + 2);
  __asm { LDCL            p1, c15, [R0],#8 }
  return result;
}

//----- (0000267C) --------------------------------------------------------
int __fastcall sub_267C(_DWORD *a1)
{
  int *v5; // r0@1
  int result; // r0@1

  _T1 = *a1;
  v5 = a1 + 1;
  __asm { LDC2            p1, c8, [R0],#4 }
  _T1 = *v5;
  ++v5;
  __asm { LDC2            p1, c9, [R0],#4 }
  _T1 = *v5;
  ++v5;
  __asm { LDC2            p1, c10, [R0],#4 }
  _T1 = *v5;
  result = (int)(v5 + 1);
  __asm { LDC2            p1, c11, [R0],#4 }
  return result;
}

//----- (00002690) --------------------------------------------------------
signed int __fastcall j_j_j_hw_set_colortemperature(int _R0)
{
  return j_j_hw_set_colortemperature(_R0);
}

//----- (00002694) --------------------------------------------------------
signed int __fastcall j_j_hw_set_colortemperature(int _R0)
{
  return j_hw_set_colortemperature(_R0);
}

//----- (000026A0) --------------------------------------------------------
signed int __fastcall j_j_j_hw_update_rgb_gamma(int a1, int _R1, int _R2)
{
  return j_j_hw_update_rgb_gamma(a1, _R1, _R2);
}

//----- (000026A4) --------------------------------------------------------
signed int __fastcall j_j_hw_update_rgb_gamma(int a1, int _R1, int _R2)
{
  return j_hw_update_rgb_gamma(a1, _R1, _R2);
}

//----- (000026B0) --------------------------------------------------------
int __fastcall j_j_j_hw_set_comfort_mode(unsigned int a1)
{
  return j_j_hw_set_comfort_mode(a1);
}

//----- (000026B4) --------------------------------------------------------
int __fastcall j_j_hw_set_comfort_mode(unsigned int a1)
{
  return j_hw_set_comfort_mode(a1);
}

//----- (000026C0) --------------------------------------------------------
int __fastcall j_j_j_hw_get_smart_display_supported(_DWORD *a1)
{
  return j_j_hw_get_smart_display_supported(a1);
}

//----- (000026C4) --------------------------------------------------------
int __fastcall j_j_hw_get_smart_display_supported(_DWORD *a1)
{
  return j_hw_get_smart_display_supported(a1);
}

//----- (000026D0) --------------------------------------------------------
int j_j_j_hw_update_color_temp_for_rg_led()
{
  return j_j_hw_update_color_temp_for_rg_led();
}

//----- (000026D4) --------------------------------------------------------
int j_j_hw_update_color_temp_for_rg_led()
{
  return j_hw_update_color_temp_for_rg_led();
}

//----- (000026E0) --------------------------------------------------------
signed int j_j_j_hw_set_color_mode()
{
  return j_j_hw_set_color_mode();
}

//----- (000026E4) --------------------------------------------------------
signed int j_j_hw_set_color_mode()
{
  return j_hw_set_color_mode();
}

//----- (000026F0) --------------------------------------------------------
void sub_26F0()
{
  sub_26F4();
}

//----- (000026F4) --------------------------------------------------------
void sub_26F4()
{
  JUMPOUT(sub_260C);
}
// 260C: using guessed type int sub_260C();

//----- (00002700) --------------------------------------------------------
int __fastcall sub_2700(_DWORD *a1)
{
  return sub_2704(a1);
}

//----- (00002704) --------------------------------------------------------
int __fastcall sub_2704(_DWORD *a1)
{
  return sub_267C(a1);
}

// ALL OK, 76 function(s) have been successfully decompiled
