/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2015 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

// int __fastcall _cxa_finalize(_DWORD); weak
// int ioctl(int fd, unsigned __int32 request, ...);
// int __cdecl _errno(_DWORD, _DWORD, _DWORD, _DWORD); weak
// char *strerror(int errnum);
// int _android_log_print(_DWORD, _DWORD, const char *, ...); weak
// int open(const char *file, int oflag, ...);
// int close(int fd);
// void *memset(void *s, int c, size_t n);
// void *mmap(void *addr, size_t len, int prot, int flags, int fd, __off_t offset);
int __fastcall j_ion_alloc(int a1, int a2, int a3, int a4, int a5, _DWORD *a6);
int __fastcall j_ion_share(int a1, int a2, _DWORD *a3);
int __fastcall j_ion_free(int a1, int a2, int a3);
// void abort(void);
// int fprintf(FILE *stream, const char *format, ...);
// int __fastcall _aeabi_memcpy(_DWORD); weak
// int __fastcall _aeabi_memset(_DWORD, _DWORD, _DWORD); weak
// int dladdr(void); weak
// int __fastcall _snprintf_chk(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int __fastcall _gnu_Unwind_Find_exidx(_DWORD, _DWORD); weak
int sub_934();
int (*__fastcall sub_954(int (*result)(void)))(void);
int __fastcall sub_A14(int a1, unsigned __int32 a2);
int ion_open();
int __fastcall ion_alloc(int a1, int a2, int a3, int a4, int a5, _DWORD *a6);
int __fastcall ion_free(int a1, int a2, int a3);
int __fastcall ion_map(int flags, __off_t a2, int a3, int a4, int flagsa, __off_t a6, _DWORD *a7, _DWORD *a8);
int __fastcall ion_share(int a1, int a2, _DWORD *a3);
int __fastcall ion_alloc_fd(int a1, int a2, int a3, int a4, int a5, _DWORD *a6);
int __fastcall ion_import(int a1, int a2, _DWORD *a3);
int __fastcall ion_sync_fd(int a1);
int __fastcall ion_invalidate_fd(int a1);
int __fastcall ion_get_phys(int a1, int a2, _DWORD *a3);
signed int __fastcall ion_map_iommu(int a1, int a2, _DWORD *a3);
signed int __fastcall ion_unmap_iommu(int a1, int a2, int *a3);
signed int __fastcall sub_EA0(int a1, int a2, unsigned int a3, unsigned int a4);
signed int __fastcall sub_11E4(int a1, int a2, unsigned int a3, int a4, int *a5);
signed int __fastcall sub_1288(int a1, int a2, unsigned int a3, int a4);
signed int __fastcall sub_13AC(int a1, int a2, int a3);
void sub_1400();
void sub_1408();
signed int __fastcall sub_14A4(int a1, int a2, char a3);
void __fastcall sub_15C0(int a1, int a2, int a3);
int __fastcall sub_1644(int a1, int a2, int a3, int a4, int a5);
int __fastcall sub_165C(int _R0);
int __fastcall sub_1664(int _R0);
int __fastcall sub_166C(int _R0);
void sub_1674();
void sub_16B8();
int __fastcall sub_16CC(int a1);
signed int __fastcall sub_171C(int a1, int a2, _DWORD *a3);
signed int __fastcall sub_174C(int a1, int a2, int a3);
signed int __fastcall sub_1790(int a1, int a2, _QWORD *a3);
signed int __fastcall sub_17C0(int a1, int a2, int a3, int a4);
int __fastcall sub_17F8(int a1);
signed int __fastcall sub_1800(int a1, int a2);
signed int __fastcall sub_1820(int a1);
int __fastcall sub_1838(int a1);
int __fastcall sub_1848(int a1, int a2);
int __fastcall sub_186C(int a1, signed int a2);
int __fastcall sub_1908(int result, signed int a2, int a3);
int __fastcall sub_19A0(int a1, int a2);
__int64 __fastcall sub_19C4(int a1, int a2);
int __fastcall sub_1A74(int a1, int a2, int a3, int a4);
signed int __fastcall sub_1B48(int a1);
int __fastcall sub_1B94(int a1, int a2);
void __fastcall sub_1BD4(int a1);
int __fastcall sub_1BEC(int a1);
signed int __fastcall sub_1BF4(int a1, int a2, int a3, _DWORD *a4);
int __fastcall sub_1C50(int a1, int a2);
const char *__fastcall sub_1C9C(int a1, signed int a2);
int __fastcall sub_1CA4(int result);
void __fastcall sub_1CAC(int a1, int a2, int a3, int a4);
int __fastcall sub_1CE0(int a1);
int sub_1D30(); // weak
int __fastcall sub_1EC0(int result, int a2, int a3, _DWORD *a4, int a5, int a6, int a7, _DWORD *a8);
int sub_2598(); // weak
int __fastcall sub_25AC(int _R0);
int __fastcall sub_25B4(int _R0);
int __fastcall sub_25BC(int _R0);
int __fastcall sub_25C4(_DWORD *a1);
int __fastcall sub_2608(_DWORD *a1);
int j_j_close(int fd);
int j_close(int fd);
void sub_262C();
void sub_2630();
int __fastcall sub_263C(_DWORD *a1);
int __fastcall sub_2640(_DWORD *a1);

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN loc_13B4; // weak
void *off_4E3C = (void *)0x1841; // weak
int GLOBAL_OFFSET_TABLE_ = 0; // weak
void *off_5000 = &off_5000; // weak
_UNKNOWN unk_5004; // weak
// extern struct _IO_FILE *stderr;


//----- (000008BC) --------------------------------------------------------
int __fastcall j_ion_alloc(int a1, int a2, int a3, int a4, int a5, _DWORD *a6)
{
  return ion_alloc(a1, a2, a3, a4, a5, a6);
}

//----- (000008C8) --------------------------------------------------------
int __fastcall j_ion_share(int a1, int a2, _DWORD *a3)
{
  return ion_share(a1, a2, a3);
}

//----- (000008D4) --------------------------------------------------------
int __fastcall j_ion_free(int a1, int a2, int a3)
{
  return ion_free(a1, a2, a3);
}

//----- (00000934) --------------------------------------------------------
int sub_934()
{
  return _cxa_finalize(&off_5000);
}
// 838: using guessed type int __fastcall _cxa_finalize(_DWORD);
// 5000: using guessed type void *off_5000;

//----- (00000954) --------------------------------------------------------
int (*__fastcall sub_954(int (*result)(void)))(void)
{
  if ( result )
    result = (int (*)(void))result();
  return result;
}

//----- (00000A14) --------------------------------------------------------
int __fastcall sub_A14(int a1, unsigned __int32 a2)
{
  int v2; // r8@1
  signed __int32 v3; // r6@1
  int result; // r0@1
  signed int v5; // r1@1
  signed int v6; // r2@1
  int v7; // r5@1
  const char *v8; // r4@7
  int *v9; // r0@19
  int *v10; // r7@19
  char *v11; // r0@19

  v2 = a1;
  v3 = a2;
  result = ioctl(a1, a2);
  v7 = result;
  if ( result < 0 )
  {
    if ( v3 == -1073198843 )
    {
      v8 = "ION_IOC_IMPORT";
      goto LABEL_19;
    }
    if ( v3 > -1073198843 )
    {
      if ( v3 == -1073198841 )
      {
        v8 = "ION_IOC_SYNC";
        goto LABEL_19;
      }
      if ( v3 < -1073198841 )
      {
        v8 = "ION_IOC_CUSTOM";
        goto LABEL_19;
      }
      if ( v3 == -1072412416 )
      {
        v8 = "ION_IOC_ALLOC";
        goto LABEL_19;
      }
    }
    else
    {
      result = -1073198846;
      if ( v3 == -1073198846 )
      {
        v8 = "ION_IOC_MAP";
        goto LABEL_19;
      }
      result = -1073198844;
      if ( v3 == -1073198844 )
      {
        v8 = "ION_IOC_SHARE";
        goto LABEL_19;
      }
      v5 = -1073460988;
      v6 = -1073460991;
      if ( v3 == -1073460991 )
      {
        v8 = "ION_IOC_FREE";
LABEL_19:
        v9 = (int *)_errno(result, v5, v6, -1073198843);
        v10 = v9;
        v11 = strerror(*v9);
        _android_log_print(6, "ion", "ioctl fd %d %x(%s) failed with code %d: %s\n", v2, v3, v8, v7, v11);
        return -*v10;
      }
    }
    v8 = "unknown";
    goto LABEL_19;
  }
  return result;
}
// 868: using guessed type int __cdecl _errno(_DWORD, _DWORD, _DWORD, _DWORD);
// 880: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);

//----- (00000AE8) --------------------------------------------------------
int ion_open()
{
  int v0; // r4@1

  v0 = open("/dev/ion", 0);
  if ( v0 < 0 )
    _android_log_print(6, "ion", "open /dev/ion failed!\n");
  return v0;
}
// 880: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);

//----- (00000B1C) --------------------------------------------------------
int __fastcall ion_alloc(int a1, int a2, int a3, int a4, int a5, _DWORD *a6)
{
  int v6; // r5@1
  int v7; // r8@1
  int v8; // r7@1
  int v9; // r6@1
  int v10; // r5@1
  int s; // [sp+Ch] [bp-2Ch]@1
  int v13; // [sp+10h] [bp-28h]@1
  int v14; // [sp+14h] [bp-24h]@1
  int v15; // [sp+18h] [bp-20h]@1
  int v16; // [sp+1Ch] [bp-1Ch]@3

  v6 = a1;
  v7 = a2;
  v8 = a3;
  v9 = a4;
  memset(&s, 0, 0x14u);
  s = v7;
  v13 = v8;
  v14 = v9;
  v15 = a5;
  v10 = sub_A14(v6, 0xC0144900);
  if ( v10 >= 0 )
    *a6 = v16;
  else
    _android_log_print(6, "ion", "%s:  heap_mask: 0x%x, flags: 0x%x\n", "ion_alloc", v14, v15);
  return v10;
}
// 880: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);

//----- (00000B8C) --------------------------------------------------------
int __fastcall ion_free(int a1, int a2, int a3)
{
  int v3; // r4@1
  int v5; // [sp+4h] [bp-14h]@1
  int v6; // [sp+8h] [bp-10h]@1
  int v7; // [sp+Ch] [bp-Ch]@1

  v5 = a2;
  v6 = a3;
  v7 = a2;
  v3 = sub_A14(a1, 0xC0044901);
  if ( v3 < 0 )
    _android_log_print(6, "ion", "%s: failed! handle: %d \n", "ion_free", v7, v5, v6);
  return v3;
}
// 880: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);

//----- (00000BCC) --------------------------------------------------------
int __fastcall ion_map(int flags, __off_t a2, int a3, int a4, int flagsa, __off_t a6, _DWORD *a7, _DWORD *a8)
{
  int v8; // r8@1
  int v9; // r7@1
  int v10; // r4@1
  void *v12; // r0@4
  int v13; // r2@4
  int v14; // r3@4
  int *v15; // r0@7
  int *v16; // r8@7
  char *v17; // r0@7

  v8 = a3;
  v9 = a4;
  v10 = sub_A14(flags, 0xC0084902);
  if ( v10 >= 0 )
  {
    *a8 = 0;
    v12 = mmap(0, v8, v9, flagsa, 0, a6);
    *a7 = v12;
    if ( v12 == (void *)-1 )
    {
      v15 = (int *)_errno(0, a7, v13, v14);
      v16 = v15;
      v17 = strerror(*v15);
      _android_log_print(6, "ion", "mmap failed: %s\n", v17);
      return -*v16;
    }
  }
  else
  {
    ((void (__fastcall *)(signed int, const char *, const char *, const char *))_android_log_print)(
      6,
      "ion",
      "%s: failed! handle: %d\n",
      "ion_map");
  }
  return v10;
}
// 868: using guessed type int __cdecl _errno(_DWORD, _DWORD, _DWORD, _DWORD);
// 880: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);

//----- (00000C84) --------------------------------------------------------
int __fastcall ion_share(int a1, int a2, _DWORD *a3)
{
  _DWORD *v3; // r4@1
  int result; // r0@1

  v3 = a3;
  result = sub_A14(a1, 0xC0084904);
  if ( result >= 0 )
    *v3 = 0;
  return result;
}
// 880: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);

//----- (00000CC8) --------------------------------------------------------
int __fastcall ion_alloc_fd(int a1, int a2, int a3, int a4, int a5, _DWORD *a6)
{
  int v6; // r5@1
  int result; // r0@1
  int v8; // r4@2
  int v9; // r2@2
  int v10; // [sp+Ch] [bp-14h]@1

  v6 = a1;
  result = j_ion_alloc(a1, a2, a3, a4, a5, &v10);
  if ( result >= 0 )
  {
    v8 = j_ion_share(v6, v10, a6);
    j_ion_free(v6, v10, v9);
    result = v8;
  }
  return result;
}

//----- (00000CF8) --------------------------------------------------------
int __fastcall ion_import(int a1, int a2, _DWORD *a3)
{
  int v3; // r4@1
  _DWORD *v4; // r6@1
  int v5; // r5@1
  int v7; // [sp+4h] [bp-14h]@1

  v3 = a2;
  v4 = a3;
  v7 = a2;
  v5 = sub_A14(a1, 0xC0084905);
  if ( v5 >= 0 )
    *v4 = 0;
  else
    _android_log_print(6, "ion", "import ioctrl failed! fd: %d\n", v3, 0, v7);
  return v5;
}
// 880: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);

//----- (00000D38) --------------------------------------------------------
int __fastcall ion_sync_fd(int a1)
{
  return sub_A14(a1, 0xC0084907);
}

//----- (00000D54) --------------------------------------------------------
int __fastcall ion_invalidate_fd(int a1)
{
  return sub_A14(a1, 0xC008490A);
}

//----- (00000D70) --------------------------------------------------------
int __fastcall ion_get_phys(int a1, int a2, _DWORD *a3)
{
  _DWORD *v3; // r4@1
  int result; // r0@1
  int v5; // r0@2
  int v6; // r1@2
  int v7; // r2@2
  int v8; // r3@2
  int v9; // [sp+0h] [bp-20h]@1
  int *v10; // [sp+4h] [bp-1Ch]@1
  int v11; // [sp+8h] [bp-18h]@1
  int v12; // [sp+10h] [bp-10h]@3

  v3 = a3;
  v11 = a2;
  v9 = 0;
  v10 = &v11;
  result = ioctl(a1, 0xC0084906, &v9);
  if ( result )
  {
    v5 = _android_log_print(6, "ion", "get phys ioctrl failed!\n");
    result = -*(_DWORD *)_errno(v5, v6, v7, v8);
  }
  else
  {
    *v3 = v12;
  }
  return result;
}
// 868: using guessed type int __cdecl _errno(_DWORD, _DWORD, _DWORD, _DWORD);
// 880: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);

//----- (00000DB8) --------------------------------------------------------
signed int __fastcall ion_map_iommu(int a1, int a2, _DWORD *a3)
{
  int v3; // r7@1
  _DWORD *v4; // r4@1
  int *v5; // r3@3
  char *v6; // r2@3
  int v7; // r0@4
  int v8; // r1@4
  int *v9; // r5@4
  int v10; // r7@5
  signed int result; // r0@6
  char *v12; // r1@7
  _DWORD *v13; // r6@7
  int v14; // r0@8
  char *v15; // r4@8
  char v16; // [sp+4h] [bp-34h]@3
  char v17; // [sp+1Ch] [bp-1Ch]@8

  v3 = a1;
  v4 = a3;
  if ( a2 && a3 )
  {
    v5 = a3;
    v6 = &v16;
    do
    {
      v7 = *v5;
      v5 += 2;
      v8 = *(v5 - 1);
      *(_DWORD *)v6 = v7;
      *((_DWORD *)v6 + 1) = v8;
      v9 = (int *)(v6 + 8);
      v6 += 8;
    }
    while ( v5 != v4 + 6 );
    *v9 = *v5;
    v10 = sub_A14(v3, 0xC0204908);
    if ( v10 )
    {
      _android_log_print(6, "ion", "map iommu failed!\n");
      result = v10;
    }
    else
    {
      v12 = &v16;
      v13 = v4;
      do
      {
        v13 += 2;
        v14 = *(_DWORD *)v12;
        v15 = v12 + 8;
        *(v13 - 1) = *((_DWORD *)v12 + 1);
        v12 = v15;
        *(v13 - 2) = v14;
      }
      while ( v15 != &v17 );
      result = 0;
      *v13 = *(_DWORD *)v15;
    }
  }
  else
  {
    result = -1;
  }
  return result;
}
// 880: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);

//----- (00000E40) --------------------------------------------------------
signed int __fastcall ion_unmap_iommu(int a1, int a2, int *a3)
{
  int v3; // r5@1
  char *v4; // r3@3
  int v5; // r6@3
  int v6; // r0@4
  int v7; // r1@4
  int *v8; // r4@4
  int v9; // r5@5
  signed int result; // r0@7
  char v11; // [sp+4h] [bp-2Ch]@3

  v3 = a1;
  if ( a2 && a3 )
  {
    v4 = &v11;
    v5 = (int)(a3 + 6);
    do
    {
      v6 = *a3;
      a3 += 2;
      v7 = *(a3 - 1);
      *(_DWORD *)v4 = v6;
      *((_DWORD *)v4 + 1) = v7;
      v8 = (int *)(v4 + 8);
      v4 += 8;
    }
    while ( a3 != (int *)v5 );
    *v8 = *a3;
    v9 = sub_A14(v3, 0xC0204909);
    if ( v9 )
      _android_log_print(6, "ion", "unmap_iommu failed!\n");
    result = v9;
  }
  else
  {
    result = -1;
  }
  return result;
}
// 880: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);

//----- (00000EA0) --------------------------------------------------------
signed int __fastcall sub_EA0(int a1, int a2, unsigned int a3, unsigned int a4)
{
  unsigned int v4; // r5@1
  unsigned int v5; // r7@1
  int v6; // r10@1
  int v7; // r4@1
  int v8; // r11@2
  unsigned int v9; // r8@7
  int v10; // r9@7
  int v11; // r0@8
  int v12; // r2@9
  int v13; // r1@10
  signed int result; // r0@10
  int v15; // r3@19
  int v16; // r2@19
  int v17; // r0@19
  int v18; // r1@19
  int v19; // r2@37
  int v20; // r0@39
  int v21; // r1@39
  int v22; // r3@39
  unsigned int v23; // r1@40
  unsigned int v24; // r0@40
  int v25; // r1@42
  int v26; // r6@45
  char v27; // r1@45
  int v29; // r0@50
  unsigned int v35; // r0@51
  int v36; // [sp+4h] [bp-34h]@58
  int v37; // [sp+8h] [bp-30h]@6
  int v38; // [sp+Ch] [bp-2Ch]@22
  int v39; // [sp+10h] [bp-28h]@8

  v4 = a4;
  v5 = a3;
  v6 = a2;
  v7 = a1;
  if ( a3 >= a4 )
    goto LABEL_58;
  v8 = 0;
  do
  {
    v9 = v5 + 1;
    v10 = *(_BYTE *)(v6 + (v5 ^ 3));
    if ( !(v10 & 0x80) )
    {
      sub_171C(v7, 13, &v39);
      v11 = 4 * v10;
      if ( v10 & 0x40 )
        v12 = -4 - (v11 & 0xFC) + v39;
      else
        v12 = v11 + v39 + 4;
      v39 = v12;
LABEL_23:
      sub_174C(v7, 13, v12);
      ++v5;
      continue;
    }
    v13 = v10 & 0xF0;
    result = 9;
    if ( v13 > 159 )
    {
      if ( v13 > 191 )
      {
        if ( v13 == 192 )
        {
          switch ( v10 )
          {
            case 199:
              if ( !*(_BYTE *)(v6 + (v9 ^ 3)) || (unsigned int)*(_BYTE *)(v6 + (v9 ^ 3)) >= 0x10 )
                return 9;
              goto LABEL_55;
            case 192:
            case 193:
            case 194:
            case 195:
            case 196:
            case 197:
              v18 = 3;
              v16 = ((v10 & 7) + 1) | 0xA0000;
              v17 = v7;
              goto LABEL_33;
            case 200:
            case 201:
              v23 = *(_BYTE *)(v6 + (v9 ^ 3));
              v24 = v23 >> 4;
              if ( v10 == 200 )
                v24 = (v23 >> 4) | 0x10;
              v25 = v23 & 0xF;
              if ( (signed int)(v24 + v25) > 31 )
                return 9;
              v19 = (v25 + 1) | (v24 << 16);
              v20 = v7;
              v21 = 1;
              goto LABEL_53;
            case 198:
              v35 = *(_BYTE *)(v6 + (v9 ^ 3));
              if ( (signed int)((v35 & 0xF) + (v35 >> 4)) > 15 )
                return 9;
              v19 = ((v35 & 0xF) + 1) | (v35 >> 4 << 16);
              v20 = v7;
              v21 = 3;
LABEL_53:
              v22 = 5;
LABEL_54:
              sub_1288(v20, v21, v19, v22);
              goto LABEL_55;
            default:
              return 9;
          }
          return 9;
        }
        if ( v13 != 208 )
          return result;
        if ( v10 & 8 )
          return 9;
        v18 = 1;
        v16 = ((v10 & 7) + 1) | 0x80000;
        v17 = v7;
LABEL_33:
        v15 = 5;
      }
      else
      {
        if ( v13 != 160 )
        {
          if ( v13 != 176 )
            return result;
          result = 9;
          switch ( v10 )
          {
            case 177:
              if ( v9 >= v4 )
                return 9;
              v19 = *(_BYTE *)(v6 + (v9 ^ 3));
              result = 9;
              if ( !*(_BYTE *)(v6 + (v9 ^ 3)) || v19 & 0xF0 )
                return result;
              v20 = v7;
              v21 = 0;
              v22 = 0;
              goto LABEL_54;
            case 178:
              if ( v9 >= v4 )
                return 9;
              v5 += 2;
              v26 = 0;
              v27 = 0;
              break;
            case 179:
              v22 = 1;
              v29 = *(_BYTE *)(v6 + (v9 ^ 3));
              _R1 = v29 << 12;
              __asm { UXTB16.W        R1, R1 }
              v19 = ((v29 & 0xF) + 1) | _R1;
              v20 = v7;
              v21 = 1;
              goto LABEL_54;
            case 176:
              goto LABEL_57;
            case 180:
            case 181:
            case 182:
            case 183:
              return result;
            default:
              v18 = 1;
              v15 = 1;
              v16 = ((v10 & 7) + 1) | 0x80000;
              v17 = v7;
              goto LABEL_34;
          }
          while ( 1 )
          {
            v26 |= (*(_BYTE *)(v6 + ((v5 - 1) ^ 3)) & 0x7F) << v27;
            if ( !(*(_BYTE *)(v6 + ((v5 - 1) ^ 3)) & 0x80) )
              break;
            _CF = v5 >= v4;
            v27 += 7;
            result = 9;
            ++v5;
            if ( _CF )
              return result;
          }
          sub_171C(v7, 13, &v37);
          v37 += 4 * v26 + 516;
          sub_174C(v7, 13, v37);
          continue;
        }
        v15 = 0;
        v16 = ((16 << ((*(_BYTE *)(v6 + (v5 ^ 3)) & 7) + 1)) - 16) | (*(_BYTE *)(v6 + (v5 ^ 3)) << 11) & 0x4000;
        v17 = v7;
        v18 = 0;
      }
LABEL_34:
      sub_1288(v17, v18, v16, v15);
      ++v5;
      continue;
    }
    if ( v13 != 128 )
    {
      if ( v13 != 144 )
        return result;
      if ( (v10 & 0xF | 2) == 15 )
        return 9;
      sub_171C(v7, v10 & 0xF, &v38);
      v12 = v38;
      goto LABEL_23;
    }
    if ( v9 >= v4 || !((unsigned __int16)((_WORD)v10 << 12) | 16 * *(_BYTE *)(v6 + ((v5 + 1) ^ 3))) )
      return 9;
    sub_1288(v7, 0, (unsigned __int16)((_WORD)v10 << 12) | 16 * *(_BYTE *)(v6 + (v9 ^ 3)), 0);
    v8 |= (((_WORD)v10 << 12) & 0x8000u) >> 15;
LABEL_55:
    v5 += 2;
  }
  while ( v5 < v4 );
LABEL_57:
  if ( v8 & 1 )
    return 8;
LABEL_58:
  sub_171C(v7, 14, &v36);
  sub_174C(v7, 15, v36);
  return 8;
}

//----- (000011E4) --------------------------------------------------------
signed int __fastcall sub_11E4(int a1, int a2, unsigned int a3, int a4, int *a5)
{
  int v5; // r5@1
  int v6; // r4@1
  signed int result; // r0@2
  int v8; // r2@4
  int v9; // r0@4
  int v10; // r1@4
  __int64 v11; // r2@10
  int v12; // r1@10

  v5 = a3;
  v6 = a1;
  switch ( a2 )
  {
    case 0:
      result = 2;
      if ( a3 > 0xF || a4 )
        return result;
      v8 = *a5;
      v9 = v6;
      v10 = v5;
      goto LABEL_14;
    case 1:
      if ( a4 == 5 )
      {
        if ( a3 <= 0x1F )
          goto LABEL_21;
        return 2;
      }
      if ( a4 != 1 || a3 > 0xF )
        return 2;
      sub_1838(a1);
LABEL_21:
      v11 = *(_QWORD *)a5;
      v12 = v5 + 256;
LABEL_22:
      result = sub_17C0(v6, v12, v11, SHIDWORD(v11));
LABEL_23:
      if ( result )
        result = 2;
      return result;
    case 3:
      result = 2;
      if ( a3 > 0x1F || a4 != 5 )
        return result;
      v11 = *(_QWORD *)a5;
      v12 = v5 + 112;
      goto LABEL_22;
    case 4:
      result = 2;
      if ( a3 > 3 || a4 )
        return result;
      v8 = *a5;
      v10 = v5 + 192;
      v9 = v6;
LABEL_14:
      result = sub_174C(v9, v10, v8);
      goto LABEL_23;
    default:
      sub_15C0(
        (int)"_Unwind_VRS_Result _Unwind_VRS_Set(_Unwind_Context *, _Unwind_VRS_RegClass, uint32_t, _Unwind_VRS_DataRepre"
             "sentation, void *)",
        831,
        (int)"unsupported register class");
      return result;
  }
}

//----- (00001288) --------------------------------------------------------
signed int __fastcall sub_1288(int a1, int a2, unsigned int a3, int a4)
{
  int v4; // r5@1
  int v5; // r7@1
  unsigned int v6; // r6@1
  int v7; // r8@1
  int v8; // r4@4
  unsigned int v9; // r7@4
  int *v10; // r0@6
  signed int v11; // r0@6
  signed int v12; // r1@6
  signed int v13; // r2@6
  signed int result; // r0@14
  unsigned int v15; // r4@18
  unsigned int v16; // r6@18
  int v17; // r0@19
  int v18; // r2@19
  int v19; // r0@19
  int v20; // r2@22
  int v21; // [sp+8h] [bp-38h]@19
  int v22; // [sp+Ch] [bp-34h]@19
  int v23; // [sp+14h] [bp-2Ch]@16
  int v24; // [sp+18h] [bp-28h]@6
  int *v25; // [sp+1Ch] [bp-24h]@3

  v4 = a2;
  v5 = a4;
  v6 = a3;
  v7 = a1;
  switch ( a2 )
  {
    case 0:
    case 4:
      if ( a4 || sub_171C(a1, 13, &v25) )
        return 2;
      v8 = 0;
      v9 = 0;
      do
      {
        if ( (1 << v9) & v6 )
        {
          v10 = v25;
          ++v25;
          v24 = *v10;
          v11 = sub_11E4(v7, v4, v9, 0, &v24);
          v12 = 0;
          v13 = 0;
          if ( v9 == 13 )
            v12 = 1;
          if ( !v4 )
            v13 = 1;
          if ( v11 )
            return 2;
          v8 |= v13 & v12;
        }
        ++v9;
      }
      while ( v9 < 0x10 );
      if ( v8 & 1 )
        return 0;
      v20 = (int)v25;
      goto LABEL_28;
    case 1:
    case 3:
      if ( (a4 | 4) != 5 || sub_171C(a1, 13, &v23) )
        return 2;
      if ( !(_WORD)v6 )
        goto LABEL_21;
      v15 = v6 >> 16;
      v16 = (v6 >> 16) + v6;
      break;
    default:
      sub_15C0(
        (int)"_Unwind_VRS_Result _Unwind_VRS_Pop(_Unwind_Context *, _Unwind_VRS_RegClass, uint32_t, _Unwind_VRS_DataRepresentation)",
        965,
        (int)"unsupported register class");
      return result;
  }
  do
  {
    v17 = v23;
    v23 += 4;
    v18 = *(_DWORD *)v17;
    v23 = v17 + 8;
    v19 = *(_DWORD *)(v17 + 4);
    v21 = v18;
    v22 = v19;
    if ( sub_11E4(v7, v4, v15, v5, &v21) )
      return 2;
    ++v15;
  }
  while ( v15 < v16 );
LABEL_21:
  if ( v5 == 1 )
  {
    v20 = v23 + 4;
    v23 += 4;
  }
  else
  {
    v20 = v23;
  }
LABEL_28:
  result = sub_174C(v7, 13, v20);
  if ( result )
    result = 2;
  return result;
}

//----- (000013AC) --------------------------------------------------------
signed int __fastcall sub_13AC(int a1, int a2, int a3)
{
  int v3; // r0@1
  int v4; // r1@1
  unsigned int *v5; // r12@1
  int v6; // r3@1
  unsigned int v7; // r3@4
  unsigned int v8; // r2@4

  v3 = a2;
  v4 = a3;
  v5 = *(unsigned int **)(v3 + 76);
  v6 = (*v5 >> 24) & 0xF;
  if ( v6 )
  {
    if ( v6 != 1 && v6 != 3 )
      return 9;
    v7 = 4 * ((*v5 >> 16) & 0xFF) + 4;
    v8 = 2;
  }
  else
  {
    v8 = 1;
    v7 = 4;
  }
  if ( !v5 || !(*(_BYTE *)(v3 + 80) & 1) && *(unsigned int *)((char *)v5 + v7) )
    return 9;
  return sub_EA0(v4, (int)v5, v8, v7);
}

//----- (00001400) --------------------------------------------------------
void sub_1400()
{
  JUMPOUT(&loc_13B4);
}

//----- (00001408) --------------------------------------------------------
void sub_1408()
{
  JUMPOUT(&loc_13B4);
}

//----- (000014A4) --------------------------------------------------------
signed int __fastcall sub_14A4(int a1, int a2, char a3)
{
  int v3; // r4@1
  char v4; // r10@1
  signed int i; // r6@1
  signed int v6; // r7@3
  int v7; // r0@8
  int (__fastcall *v8)(signed int, int, char *); // r3@11
  int v9; // r0@12
  int v11; // [sp+0h] [bp-4B0h]@17
  int v12; // [sp+4h] [bp-4ACh]@10
  int (__fastcall *v13)(signed int, int, char *); // [sp+10h] [bp-4A0h]@11
  int v14; // [sp+18h] [bp-498h]@12
  int v15; // [sp+24h] [bp-48Ch]@12
  int v16; // [sp+2Ch] [bp-484h]@10
  char v17; // [sp+30h] [bp-480h]@1

  v3 = a2;
  v4 = a3;
  sub_16CC((int)&v17);
  for ( i = 1; ; --i )
  {
    v6 = 1;
    if ( v4 & 1 )
    {
      v6 = 2;
      if ( !i )
      {
        sub_174C((int)&v17, -1, *(_DWORD *)(v3 + 16));
        v4 = 0;
      }
    }
    v7 = sub_17F8((int)&v17);
    if ( !v7 )
      break;
    if ( v7 < 0 )
      return 2;
    sub_171C((int)&v17, -2, &v16);
    if ( sub_1800((int)&v17, (int)&v12) )
      return 2;
    v8 = v13;
    if ( v13 )
    {
      *(_DWORD *)(v3 + 72) = v12;
      *(_DWORD *)(v3 + 76) = v15;
      *(_DWORD *)(v3 + 80) = v14;
      v9 = v8(v6, v3, &v17);
      if ( v9 == 7 )
      {
        sub_171C((int)&v17, -1, &v11);
        *(_DWORD *)(v3 + 16) = v11;
        sub_1820((int)&v17);
        return 2;
      }
      if ( v9 == 9 )
        abort();
      if ( v9 != 8 )
        return 2;
      if ( v16 == *(_DWORD *)(v3 + 32) )
        sub_15C0(
          (int)"_Unwind_Reason_Code unwind_phase2(unw_context_t *, _Unwind_Exception *, bool)",
          642,
          (int)"during phase1 personality function said it would stop here, but now in phase2 it did not stop here");
    }
  }
  return 5;
}

//----- (000015C0) --------------------------------------------------------
void __fastcall sub_15C0(int a1, int a2, int a3)
{
  fprintf((FILE *)stderr, "libunwind: %s %s:%d - %s\n", a1, "external/libcxxabi/src/Unwind/Unwind-EHABI.cpp", a2, a3);
  abort();
}

//----- (00001644) --------------------------------------------------------
int __fastcall sub_1644(int a1, int a2, int a3, int a4, int a5)
{
  int v5; // r4@0
  int v6; // r5@0
  int v7; // r6@0
  int v8; // r7@0
  int v9; // r8@0
  int v10; // r9@0
  int v11; // r10@0
  int v12; // r11@0
  int v13; // r12@0
  int v14; // lr@0

  *(_DWORD *)a1 = a1;
  *(_DWORD *)(a1 + 4) = a2;
  *(_DWORD *)(a1 + 8) = a3;
  *(_DWORD *)(a1 + 12) = a4;
  *(_DWORD *)(a1 + 16) = v5;
  *(_DWORD *)(a1 + 20) = v6;
  *(_DWORD *)(a1 + 24) = v7;
  *(_DWORD *)(a1 + 28) = v8;
  *(_DWORD *)(a1 + 32) = v9;
  *(_DWORD *)(a1 + 36) = v10;
  *(_DWORD *)(a1 + 40) = v11;
  *(_DWORD *)(a1 + 44) = v12;
  *(_DWORD *)(a1 + 48) = v13;
  *(_DWORD *)(a1 + 52) = &a5;
  *(_DWORD *)(a1 + 56) = v14;
  *(_DWORD *)(a1 + 60) = v14;
  return 0;
}

//----- (0000165C) --------------------------------------------------------
int __fastcall sub_165C(int _R0)
{
  int result; // r0@1

  __asm { VSTMIA          R0, {D0-D15} }
  return result;
}

//----- (00001664) --------------------------------------------------------
int __fastcall sub_1664(int _R0)
{
  int result; // r0@1

  __asm { VSTMIA          R0, {D0-D15} }
  return result;
}

//----- (0000166C) --------------------------------------------------------
int __fastcall sub_166C(int _R0)
{
  int result; // r0@1

  __asm { VSTMIA          R0, {D16-D31} }
  return result;
}

//----- (00001674) --------------------------------------------------------
void sub_1674()
{
  __asm
  {
    STCL            p1, c0, [R0],#8
    STCL            p1, c1, [R0],#8
    STCL            p1, c2, [R0],#8
    STCL            p1, c3, [R0],#8
    STCL            p1, c4, [R0],#8
    STCL            p1, c5, [R0],#8
    STCL            p1, c6, [R0],#8
    STCL            p1, c7, [R0],#8
    STCL            p1, c8, [R0],#8
    STCL            p1, c9, [R0],#8
    STCL            p1, c10, [R0],#8
    STCL            p1, c11, [R0],#8
    STCL            p1, c12, [R0],#8
    STCL            p1, c13, [R0],#8
    STCL            p1, c14, [R0],#8
    STCL            p1, c15, [R0],#8
  }
}

//----- (000016B8) --------------------------------------------------------
void sub_16B8()
{
  __asm
  {
    STC2            p1, c8, [R0],#4
    STC2            p1, c9, [R0],#4
    STC2            p1, c10, [R0],#4
    STC2            p1, c11, [R0],#4
  }
}

//----- (000016CC) --------------------------------------------------------
int __fastcall sub_16CC(int a1)
{
  int v1; // r4@1

  v1 = a1;
  *(_DWORD *)a1 = &off_4E3C;
  *(_DWORD *)(a1 + 4) = &unk_5004;
  *(_BYTE *)(a1 + 76) = 0;
  *(_DWORD *)(a1 + 72) = 0;
  _aeabi_memcpy(a1 + 8);
  _aeabi_memset(v1 + 80, 450, 0);
  sub_1C50(v1, 0);
  return 0;
}
// 8F8: using guessed type int __fastcall _aeabi_memcpy(_DWORD);
// 904: using guessed type int __fastcall _aeabi_memset(_DWORD, _DWORD, _DWORD);
// 4E3C: using guessed type void *;

//----- (0000171C) --------------------------------------------------------
signed int __fastcall sub_171C(int a1, int a2, _DWORD *a3)
{
  int v3; // r6@1
  _DWORD *v4; // r4@1
  int v5; // r5@1
  signed int result; // r0@2

  v3 = a1;
  v4 = a3;
  v5 = a2;
  if ( (*(int (**)(void))(*(_DWORD *)a1 + 8))() == 1 )
  {
    *v4 = (*(int (__fastcall **)(int, int))(*(_DWORD *)v3 + 12))(v3, v5);
    result = 0;
  }
  else
  {
    result = -6542;
  }
  return result;
}

//----- (0000174C) --------------------------------------------------------
signed int __fastcall sub_174C(int a1, int a2, int a3)
{
  int v3; // r4@1
  int v4; // r6@1
  int v5; // r5@1
  signed int v6; // r5@3

  v3 = a1;
  v4 = a3;
  v5 = a2;
  if ( (*(int (**)(void))(*(_DWORD *)a1 + 8))() == 1 )
  {
    (*(void (__fastcall **)(int, int, int))(*(_DWORD *)v3 + 16))(v3, v5, v4);
    if ( v5 == -1 )
    {
      v6 = 0;
      (*(void (__fastcall **)(int, _DWORD))(*(_DWORD *)v3 + 52))(v3, 0);
    }
    else
    {
      v6 = 0;
    }
  }
  else
  {
    v6 = -6542;
  }
  return v6;
}

//----- (00001790) --------------------------------------------------------
signed int __fastcall sub_1790(int a1, int a2, _QWORD *a3)
{
  int v3; // r6@1
  _QWORD *v4; // r4@1
  int v5; // r5@1
  __int64 v6; // r0@2
  signed int result; // r0@2

  v3 = a1;
  v4 = a3;
  v5 = a2;
  if ( (*(int (**)(void))(*(_DWORD *)a1 + 20))() == 1 )
  {
    LODWORD(v6) = (*(int (__fastcall **)(int, int))(*(_DWORD *)v3 + 24))(v3, v5);
    *v4 = v6;
    result = 0;
  }
  else
  {
    result = -6542;
  }
  return result;
}

//----- (000017C0) --------------------------------------------------------
signed int __fastcall sub_17C0(int a1, int a2, int a3, int a4)
{
  int v4; // r7@1
  int v5; // r5@1
  int v6; // r6@1
  int v7; // r8@1
  signed int result; // r0@2

  v4 = a1;
  v5 = a3;
  v6 = a2;
  v7 = a4;
  if ( (*(int (**)(void))(*(_DWORD *)a1 + 20))() == 1 )
  {
    (*(void (__fastcall **)(int, int, int, int))(*(_DWORD *)v4 + 28))(v4, v6, v5, v7);
    result = 0;
  }
  else
  {
    result = -6542;
  }
  return result;
}

//----- (000017F8) --------------------------------------------------------
int __fastcall sub_17F8(int a1)
{
  return (*(int (**)(void))(*(_DWORD *)a1 + 32))();
}

//----- (00001800) --------------------------------------------------------
signed int __fastcall sub_1800(int a1, int a2)
{
  int v2; // r4@1
  signed int result; // r0@1

  v2 = a2;
  (*(void (**)(void))(*(_DWORD *)a1 + 36))();
  result = 0;
  if ( !*(_DWORD *)(v2 + 4) )
    result = -6549;
  return result;
}

//----- (00001820) --------------------------------------------------------
signed int __fastcall sub_1820(int a1)
{
  (*(void (**)(void))(*(_DWORD *)a1 + 40))();
  return -6540;
}

//----- (00001838) --------------------------------------------------------
int __fastcall sub_1838(int a1)
{
  return (*(int (**)(void))(*(_DWORD *)a1 + 60))();
}

//----- (00001848) --------------------------------------------------------
int __fastcall sub_1848(int a1, int a2)
{
  signed int v2; // r2@1
  bool v3; // zf@1
  signed int v4; // r0@1
  unsigned int v5; // r1@1

  v2 = 0;
  v3 = (a2 & 0xFFFFFFFC) == 192;
  v4 = 0;
  v5 = a2 - 16;
  if ( v3 )
    v4 = 1;
  if ( v5 > 0xFFFFFFED )
    v2 = 1;
  return v4 | v2;
}

//----- (0000186C) --------------------------------------------------------
int __fastcall sub_186C(int a1, signed int a2)
{
  signed int v2; // r5@1
  int v3; // r4@1
  int v4; // r0@7

  v2 = a2;
  v3 = a1;
  if ( a2 >= -1 )
  {
    if ( a2 > 13 )
    {
      if ( a2 == 14 )
      {
        v4 = a1 + 64;
        return *(_DWORD *)v4;
      }
      if ( a2 != 15 )
        goto LABEL_12;
    }
    else if ( a2 != -1 )
    {
      if ( a2 != 13 )
        goto LABEL_12;
LABEL_7:
      v4 = a1 + 60;
      return *(_DWORD *)v4;
    }
    v4 = a1 + 68;
    return *(_DWORD *)v4;
  }
  if ( a2 == -2 )
    goto LABEL_7;
LABEL_12:
  if ( (unsigned int)a2 > 0xC )
  {
    if ( (a2 & 0xFFFFFFFC) != 192 )
      sub_1CAC(
        (int)"uint32_t libunwind::Registers_arm::getRegister(int)",
        (int)"external/libcxxabi/src/Unwind/Registers.hpp",
        1452,
        (int)"unsupported arm register");
    if ( !*(_BYTE *)(a1 + 76) )
    {
      *(_BYTE *)(a1 + 76) = 1;
      sub_16B8();
    }
    v4 = v3 + 4 * v2 - 296;
  }
  else
  {
    v4 = a1 + 4 * a2 + 8;
  }
  return *(_DWORD *)v4;
}

//----- (00001908) --------------------------------------------------------
int __fastcall sub_1908(int result, signed int a2, int a3)
{
  signed int v3; // r6@1
  int v4; // r4@1
  int v5; // r5@1

  v3 = a2;
  v4 = a3;
  v5 = result;
  if ( a2 >= -1 )
  {
    if ( a2 > 13 )
    {
      if ( a2 == 14 )
      {
        *(_DWORD *)(result + 64) = a3;
        return result;
      }
      if ( a2 != 15 )
        goto LABEL_12;
    }
    else if ( a2 != -1 )
    {
      if ( a2 != 13 )
        goto LABEL_12;
LABEL_7:
      *(_DWORD *)(result + 60) = a3;
      return result;
    }
    *(_DWORD *)(result + 68) = a3;
    return result;
  }
  if ( a2 == -2 )
    goto LABEL_7;
LABEL_12:
  if ( (unsigned int)a2 > 0xC )
  {
    if ( (a2 & 0xFFFFFFFC) != 192 )
      sub_1CAC(
        (int)"void libunwind::Registers_arm::setRegister(int, uint32_t)",
        (int)"external/libcxxabi/src/Unwind/Registers.hpp",
        1471,
        (int)"unsupported arm register");
    if ( !*(_BYTE *)(result + 76) )
    {
      *(_BYTE *)(result + 76) = 1;
      sub_16B8();
    }
    result = v5 + 4 * v3;
    *(_DWORD *)(result - 296) = v4;
  }
  else
  {
    result += 4 * a2;
    *(_DWORD *)(result + 8) = a3;
  }
  return result;
}

//----- (000019A0) --------------------------------------------------------
int __fastcall sub_19A0(int a1, int a2)
{
  signed int v2; // r2@1
  bool v3; // zf@1
  signed int v4; // r0@1
  unsigned int v5; // r1@1

  v2 = 0;
  v3 = (a2 & 0xFFFFFFF0) == 112;
  v4 = 0;
  v5 = a2 & 0xFFFFFFE0;
  if ( v3 )
    v4 = 1;
  if ( v5 == 256 )
    v2 = 1;
  return v4 | v2;
}

//----- (000019C4) --------------------------------------------------------
__int64 __fastcall sub_19C4(int a1, int a2)
{
  int v2; // r4@1
  int v3; // r5@1
  unsigned int v4; // r0@1
  int v5; // r0@5
  int v6; // r0@11

  v2 = a2;
  v3 = a1;
  v4 = a2 & 0xFFFFFFF0;
  if ( (a2 & 0xFFFFFFF0) == 112 )
  {
    if ( !*(_BYTE *)(v3 + 75) )
    {
      *(_BYTE *)(v3 + 75) = 1;
      sub_1674();
    }
    v5 = v3 + 8 * v2 - 552;
  }
  else if ( v4 == 272 )
  {
    if ( !*(_BYTE *)(v3 + 74) )
    {
      *(_BYTE *)(v3 + 74) = 1;
      sub_166C(v3 + 216);
    }
    v5 = v3 + 8 * v2 - 1960;
  }
  else
  {
    if ( v4 != 256 )
      sub_1CAC(
        (int)"unw_fpreg_t libunwind::Registers_arm::getFloatRegister(int)",
        (int)"external/libcxxabi/src/Unwind/Registers.hpp",
        1673,
        (int)"Unknown ARM float register");
    if ( !*(_BYTE *)(v3 + 73) )
    {
      *(_BYTE *)(v3 + 73) = 1;
      v6 = v3 + 80;
      if ( *(_BYTE *)(v3 + 72) )
        sub_1664(v6);
      else
        sub_165C(v6);
    }
    v5 = v3 + 8 * v2 - 1968;
  }
  return *(_QWORD *)v5;
}

//----- (00001A74) --------------------------------------------------------
int __fastcall sub_1A74(int a1, int a2, int a3, int a4)
{
  int v4; // r6@1
  int v5; // r7@1
  unsigned int v6; // r0@1
  int v7; // r5@1
  int v8; // r4@1
  int result; // r0@5
  int v10; // r1@5
  int v11; // r0@11

  v4 = a2;
  v5 = a1;
  v6 = a2 & 0xFFFFFFF0;
  v7 = a4;
  v8 = a3;
  if ( (a2 & 0xFFFFFFF0) == 112 )
  {
    if ( !*(_BYTE *)(v5 + 75) )
    {
      *(_BYTE *)(v5 + 75) = 1;
      sub_1674();
    }
    result = v5 + 8 * v4;
    *(_DWORD *)(result - 548) = v7;
    LOWORD(v10) = -552;
  }
  else if ( v6 == 272 )
  {
    if ( !*(_BYTE *)(v5 + 74) )
    {
      *(_BYTE *)(v5 + 74) = 1;
      sub_166C(v5 + 216);
    }
    result = v5 + 8 * v4;
    *(_DWORD *)(result - 1828) = v7;
    LOWORD(v10) = -1832;
  }
  else
  {
    if ( v6 != 256 )
      sub_1CAC(
        (int)"void libunwind::Registers_arm::setFloatRegister(int, unw_fpreg_t)",
        (int)"external/libcxxabi/src/Unwind/Registers.hpp",
        1700,
        (int)"Unknown ARM float register");
    if ( !*(_BYTE *)(v5 + 73) )
    {
      *(_BYTE *)(v5 + 73) = 1;
      v11 = v5 + 80;
      if ( *(_BYTE *)(v5 + 72) )
        sub_1664(v11);
      else
        sub_165C(v11);
    }
    result = v5 + 8 * v4;
    *(_DWORD *)(result - 1964) = v7;
    LOWORD(v10) = -1968;
  }
  HIWORD(v10) = -1;
  *(_DWORD *)(result + v10) = v8;
  return result;
}

//----- (00001B48) --------------------------------------------------------
signed int __fastcall sub_1B48(int a1)
{
  int v1; // r4@1
  signed int result; // r0@3
  void (__fastcall *v3)(int, signed int, int); // r5@5
  int v4; // r0@5

  v1 = a1;
  if ( *(_BYTE *)(a1 + 528)
    || ((*(void (__fastcall **)(int, signed int))(*(_DWORD *)a1 + 52))(a1, 1), *(_BYTE *)(v1 + 528)) )
  {
    result = 0;
  }
  else
  {
    if ( *(_DWORD *)(v1 + 504) )
    {
      v3 = *(void (__fastcall **)(int, signed int, int))(*(_DWORD *)v1 + 16);
      v4 = (*(int (__fastcall **)(int, signed int))(*(_DWORD *)v1 + 12))(v1, -2);
      v3(v1, -2, *(_DWORD *)(v1 + 504) + v4);
    }
    result = 1;
  }
  return result;
}

//----- (00001B94) --------------------------------------------------------
int __fastcall sub_1B94(int a1, int a2)
{
  int v2; // r3@1
  int v3; // r4@1
  int v4; // r5@1
  int v5; // r12@1
  int v6; // lr@1
  int v7; // r4@1
  int v8; // r2@1
  int v9; // r3@1
  int v10; // r5@1
  int result; // r0@1

  v2 = *(_DWORD *)(a1 + 504);
  v3 = *(_DWORD *)(a1 + 496);
  v4 = *(_DWORD *)(a1 + 500);
  v5 = *(_DWORD *)(a1 + 488);
  v6 = *(_DWORD *)(a1 + 492);
  *(_DWORD *)(a2 + 20) = *(_DWORD *)(a1 + 508);
  *(_DWORD *)(a2 + 16) = v2;
  *(_DWORD *)(a2 + 12) = v4;
  *(_DWORD *)(a2 + 8) = v3;
  v7 = a2 + 24;
  *(_DWORD *)a2 = v5;
  *(_DWORD *)(a2 + 4) = v6;
  v8 = *(_DWORD *)(a1 + 512);
  v9 = *(_DWORD *)(a1 + 516);
  v10 = *(_DWORD *)(a1 + 520);
  result = *(_DWORD *)(a1 + 524);
  *(_DWORD *)(a2 + 36) = result;
  *(_DWORD *)v7 = v8;
  *(_DWORD *)(v7 + 4) = v9;
  *(_DWORD *)(v7 + 8) = v10;
  return result;
}

//----- (00001BD4) --------------------------------------------------------
void __fastcall sub_1BD4(int a1)
{
  sub_1CE0(a1 + 8);
  sub_262C();
}

//----- (00001BEC) --------------------------------------------------------
int __fastcall sub_1BEC(int a1)
{
  return *(_BYTE *)(a1 + 529);
}

//----- (00001BF4) --------------------------------------------------------
signed int __fastcall sub_1BF4(int a1, int a2, int a3, _DWORD *a4)
{
  int v4; // r6@1
  int v5; // r5@1
  _DWORD *v6; // r4@1
  int v7; // r7@1
  signed int result; // r0@3
  int v9; // [sp+10h] [bp-20h]@2
  int v10; // [sp+14h] [bp-1Ch]@3

  v4 = a2;
  v5 = a3;
  v6 = a4;
  v7 = (*(int (**)(void))(*(_DWORD *)a1 + 12))();
  if ( dladdr() && v9 )
  {
    _snprintf_chk(v4, v5, 0, -1);
    *v6 = v7 - v10;
    result = 1;
  }
  else
  {
    result = 0;
  }
  return result;
}
// 910: using guessed type int dladdr(void);
// 91C: using guessed type int __fastcall _snprintf_chk(_DWORD, _DWORD, _DWORD, _DWORD);

//----- (00001C50) --------------------------------------------------------
int __fastcall sub_1C50(int a1, int a2)
{
  int v2; // r4@1
  int v3; // r6@1
  unsigned int v4; // r5@1
  int result; // r0@5
  int v6; // [sp+4h] [bp-1Ch]@3
  int v7; // [sp+8h] [bp-18h]@3
  int v8; // [sp+Ch] [bp-14h]@1

  v2 = a1;
  v3 = a2;
  v4 = (*(int (**)(void))(*(_DWORD *)a1 + 12))() & 0xFFFFFFFE;
  v8 = 0;
  if ( v3 )
    --v4;
  v6 = _gnu_Unwind_Find_exidx(v4, &v8);
  v7 = v8;
  if ( !v6 || !v8 || (result = ((int (__fastcall *)(int, unsigned int, int *))sub_1D30)(v2, v4, &v6)) == 0 )
  {
    result = 1;
    *(_BYTE *)(v2 + 528) = 1;
  }
  return result;
}
// 928: using guessed type int __fastcall _gnu_Unwind_Find_exidx(_DWORD, _DWORD);
// 1D30: using guessed type int sub_1D30();

//----- (00001C9C) --------------------------------------------------------
const char *__fastcall sub_1C9C(int a1, signed int a2)
{
  const char *result; // r0@2
  signed int v3; // r0@3
  int *v4; // r1@3

  if ( a2 > 255 )
  {
    switch ( a2 )
    {
      case 256:
        v3 = -8136;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 257:
        v3 = -8133;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 258:
        v3 = -8130;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 259:
        v3 = -8127;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 260:
        v3 = -8124;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 261:
        v3 = -8121;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 262:
        v3 = -8118;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 263:
        v3 = -8115;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 264:
        v3 = -8112;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 265:
        v3 = -8109;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 266:
        v3 = -8106;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 267:
        v3 = -8102;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 268:
        v3 = -8098;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 269:
        v3 = -8094;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 270:
        v3 = -8090;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 271:
        v3 = -8086;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 272:
        v3 = -8082;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 273:
        v3 = -8078;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 274:
        v3 = -8074;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 275:
        v3 = -8070;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 276:
        v3 = -8066;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 277:
        v3 = -8062;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 278:
        v3 = -8058;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 279:
        v3 = -8054;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 280:
        v3 = -8050;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 281:
        v3 = -8046;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 282:
        v3 = -8042;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 283:
        v3 = -8038;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 284:
        v3 = -8034;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 285:
        v3 = -8030;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 286:
        v3 = -8026;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 287:
        v3 = -8022;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      default:
def_200C:
        v3 = -8018;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
    }
  }
  else
  {
    result = "pc";
    switch ( a2 + 2 )
    {
      case 0:
      case 15:
        v3 = -8299;
        v4 = &GLOBAL_OFFSET_TABLE_;
        return (char *)v4 + v3;
      default:
        goto def_200C;
      case 1:
      case 17:
        return result;
      case 2:
        v3 = -8296;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 3:
        v3 = -8293;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 4:
        v3 = -8290;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 5:
        v3 = -8287;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 6:
        v3 = -8284;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 7:
        v3 = -8281;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 8:
        v3 = -8278;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 9:
        v3 = -8275;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 10:
        v3 = -8272;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 11:
        v3 = -8269;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 12:
        v3 = -8266;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 13:
        v3 = -8262;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 14:
        v3 = -8258;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 16:
        v3 = -8302;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 66:
        v3 = -8254;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 67:
        v3 = -8251;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 68:
        v3 = -8248;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 69:
        v3 = -8245;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 70:
        v3 = -8242;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 71:
        v3 = -8239;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 72:
        v3 = -8236;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 73:
        v3 = -8233;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 74:
        v3 = -8230;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 75:
        v3 = -8227;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 76:
        v3 = -8224;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 77:
        v3 = -8220;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 78:
        v3 = -8216;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 79:
        v3 = -8212;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 80:
        v3 = -8208;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 81:
        v3 = -8204;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 82:
        v3 = -8200;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 83:
        v3 = -8196;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 84:
        v3 = -8192;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 85:
        v3 = -8188;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 86:
        v3 = -8184;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 87:
        v3 = -8180;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 88:
        v3 = -8176;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 89:
        v3 = -8172;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 90:
        v3 = -8168;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 91:
        v3 = -8164;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 92:
        v3 = -8160;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 93:
        v3 = -8156;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 94:
        v3 = -8152;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 95:
        v3 = -8148;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 96:
        v3 = -8144;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
      case 97:
        v3 = -8140;
        v4 = &GLOBAL_OFFSET_TABLE_;
        break;
    }
  }
  return (char *)v4 + v3;
}
// 4FA0: using guessed type int GLOBAL_OFFSET_TABLE_;

//----- (00001CA4) --------------------------------------------------------
int __fastcall sub_1CA4(int result)
{
  *(_BYTE *)(result + 72) = 1;
  return result;
}

//----- (00001CAC) --------------------------------------------------------
void __fastcall sub_1CAC(int a1, int a2, int a3, int a4)
{
  fprintf((FILE *)stderr, "libunwind: %s %s:%d - %s\n", a1, a2, a3, a4);
  abort();
}

//----- (00001CE0) --------------------------------------------------------
int __fastcall sub_1CE0(int a1)
{
  int v1; // r4@1
  int v2; // r0@2
  int result; // r0@9

  v1 = a1;
  if ( *(_BYTE *)(a1 + 65) )
  {
    v2 = a1 + 72;
    if ( *(_BYTE *)(v1 + 64) )
      sub_25B4(v2);
    else
      sub_25AC(v2);
  }
  if ( *(_BYTE *)(v1 + 66) )
    sub_25BC(v1 + 208);
  if ( *(_BYTE *)(v1 + 67) )
    sub_25C4((_DWORD *)(v1 + 336));
  result = *(_BYTE *)(v1 + 68);
  if ( *(_BYTE *)(v1 + 68) )
    result = sub_263C((_DWORD *)(v1 + 464));
  return result;
}

//----- (00001EC0) --------------------------------------------------------
int __fastcall sub_1EC0(int result, int a2, int a3, _DWORD *a4, int a5, int a6, int a7, _DWORD *a8)
{
  unsigned int v8; // r4@1
  unsigned int v9; // r5@2
  int v10; // r6@3

  v8 = a5 - a2;
  while ( 1 )
  {
    v9 = v8;
    if ( !v8 )
      break;
    v10 = a2 + (v8 >> 1);
    v8 >>= 1;
    if ( *a8 >= *a4 + 8 * v10 + (2 * *(_DWORD *)(*a4 + 8 * v10) & 0x80000000 | *(_DWORD *)(*a4 + 8 * v10)) )
    {
      v8 = v9 - 1 - v8;
      a2 = v10 + 1;
    }
  }
  *(_DWORD *)result = a2;
  *(_DWORD *)(result + 4) = a3;
  *(_DWORD *)(result + 8) = a4;
  return result;
}

//----- (000025AC) --------------------------------------------------------
int __fastcall sub_25AC(int _R0)
{
  int result; // r0@1

  __asm { VLDMIA          R0, {D0-D15} }
  return result;
}

//----- (000025B4) --------------------------------------------------------
int __fastcall sub_25B4(int _R0)
{
  int result; // r0@1

  __asm { VLDMIA          R0, {D0-D15} }
  return result;
}

//----- (000025BC) --------------------------------------------------------
int __fastcall sub_25BC(int _R0)
{
  int result; // r0@1

  __asm { VLDMIA          R0, {D16-D31} }
  return result;
}

//----- (000025C4) --------------------------------------------------------
int __fastcall sub_25C4(_DWORD *a1)
{
  int *v5; // r0@1
  int result; // r0@1

  _T1 = *a1;
  v5 = a1 + 2;
  __asm { LDCL            p1, c0, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c1, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c2, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c3, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c4, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c5, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c6, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c7, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c8, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c9, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c10, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c11, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c12, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c13, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c14, [R0],#8 }
  _T1 = *v5;
  result = (int)(v5 + 2);
  __asm { LDCL            p1, c15, [R0],#8 }
  return result;
}

//----- (00002608) --------------------------------------------------------
int __fastcall sub_2608(_DWORD *a1)
{
  int *v5; // r0@1
  int result; // r0@1

  _T1 = *a1;
  v5 = a1 + 1;
  __asm { LDC2            p1, c8, [R0],#4 }
  _T1 = *v5;
  ++v5;
  __asm { LDC2            p1, c9, [R0],#4 }
  _T1 = *v5;
  ++v5;
  __asm { LDC2            p1, c10, [R0],#4 }
  _T1 = *v5;
  result = (int)(v5 + 1);
  __asm { LDC2            p1, c11, [R0],#4 }
  return result;
}

//----- (0000261C) --------------------------------------------------------
int j_j_close(int fd)
{
  return j_close(fd);
}

//----- (00002620) --------------------------------------------------------
int j_close(int fd)
{
  return close(fd);
}

//----- (0000262C) --------------------------------------------------------
void sub_262C()
{
  sub_2630();
}

//----- (00002630) --------------------------------------------------------
void sub_2630()
{
  JUMPOUT(sub_2598);
}
// 2598: using guessed type int sub_2598();

//----- (0000263C) --------------------------------------------------------
int __fastcall sub_263C(_DWORD *a1)
{
  return sub_2640(a1);
}

//----- (00002640) --------------------------------------------------------
int __fastcall sub_2640(_DWORD *a1)
{
  return sub_2608(a1);
}

// ALL OK, 69 function(s) have been successfully decompiled
